-- Dagon - instalacion limpia de base de datos
-- Script oficial de estructura para ambientes nuevos.
--
-- Orden recomendado:
--   1. Ejecutar este archivo como usuario con permisos de creacion.
--   2. Ejecutar scripts/01_datos_semilla.sql.
--   3. Ejecutar scripts/02_ejercicios_semilla.sql.
--   4. Ejecutar scripts/migraciones/*.sql en orden cronologico.
--
-- Este archivo NO contiene usuarios reales, intentos, password_hash reales ni
-- esquemas sandbox_usuario_<uuid>. El respaldo bruto queda solo como evidencia
-- historica y no como fuente de instalacion limpia.

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE SCHEMA IF NOT EXISTS lms_core;
CREATE SCHEMA IF NOT EXISTS lms_sandbox;
CREATE SCHEMA IF NOT EXISTS lms_sandbox_template;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_backend_user') THEN
        CREATE ROLE app_backend_user LOGIN;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_sandbox_user') THEN
        CREATE ROLE app_sandbox_user LOGIN;
    END IF;
END;
$$;

CREATE DOMAIN lms_core.email_valido AS text
    CONSTRAINT email_valido_check
    CHECK (VALUE ~* '^[A-Za-z0-9._%-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$');

CREATE TABLE lms_core.roles (
    id_rol integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre text NOT NULL UNIQUE,
    CONSTRAINT roles_nombre_check CHECK (nombre IN ('alumno', 'docente', 'admin'))
);

CREATE TABLE lms_core.usuarios (
    id_usuario uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    nombre text NOT NULL,
    email lms_core.email_valido NOT NULL,
    password_hash text NOT NULL,
    id_rol integer REFERENCES lms_core.roles(id_rol) ON DELETE RESTRICT,
    activo boolean NOT NULL DEFAULT true,
    fecha_registro timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    racha_actual integer NOT NULL DEFAULT 0,
    ultima_practica date,
    mejor_racha integer NOT NULL DEFAULT 0,
    metodo_auth character varying(20) DEFAULT 'local',
    CONSTRAINT usuarios_racha_actual_check CHECK (racha_actual >= 0),
    CONSTRAINT usuarios_mejor_racha_check CHECK (mejor_racha >= 0),
    CONSTRAINT usuarios_mejor_racha_consistente_check CHECK (mejor_racha >= racha_actual OR mejor_racha = 0)
);

ALTER TABLE lms_core.usuarios
    ADD CONSTRAINT usuarios_email_key UNIQUE (email);

CREATE UNIQUE INDEX idx_usuarios_email_lower_unique
    ON lms_core.usuarios (lower(email::text));

CREATE TABLE lms_core.materias (
    slug varchar(30) PRIMARY KEY,
    nombre text NOT NULL,
    descripcion text,
    orden integer NOT NULL DEFAULT 0,
    activa boolean NOT NULL DEFAULT true
);

INSERT INTO lms_core.materias (slug, nombre, descripcion, orden) VALUES
    ('sql', 'Bases de Datos SQL', 'SQL y PostgreSQL: consultas, modelado, transacciones y rendimiento', 1),
    ('io', 'Investigación de Operaciones', 'Programación lineal, simplex, transporte, redes, inventarios, colas y Markov — plan UNACH', 2);

CREATE TABLE lms_core.cursos (
    id_curso integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo text NOT NULL UNIQUE,
    materia_slug varchar(30) NOT NULL DEFAULT 'sql' REFERENCES lms_core.materias(slug)
);

CREATE TABLE lms_core.modulos (
    id_modulo integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_curso integer REFERENCES lms_core.cursos(id_curso) ON DELETE CASCADE,
    titulo text NOT NULL,
    orden integer NOT NULL,
    descripcion text,
    xp_requerida integer NOT NULL DEFAULT 0,
    objetivos jsonb NOT NULL DEFAULT '[]'::jsonb,
    prerequisitos jsonb NOT NULL DEFAULT '[]'::jsonb,
    errores_comunes jsonb NOT NULL DEFAULT '[]'::jsonb,
    cinematica_config jsonb NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT modulos_orden_check CHECK (orden > 0),
    CONSTRAINT modulos_xp_requerida_check CHECK (xp_requerida >= 0),
    CONSTRAINT modulos_objetivos_array_check CHECK (jsonb_typeof(objetivos) = 'array'),
    CONSTRAINT modulos_prerequisitos_array_check CHECK (jsonb_typeof(prerequisitos) = 'array'),
    CONSTRAINT modulos_errores_comunes_array_check CHECK (jsonb_typeof(errores_comunes) = 'array'),
    CONSTRAINT modulos_cinematica_object_check CHECK (jsonb_typeof(cinematica_config) = 'object'),
    CONSTRAINT modulos_id_curso_orden_key UNIQUE (id_curso, orden)
);

CREATE TABLE lms_core.grupos_docente (
    id_grupo BIGSERIAL PRIMARY KEY,
    id_docente UUID NOT NULL REFERENCES lms_core.usuarios(id_usuario),
    nombre_grupo VARCHAR(120) NOT NULL,
    codigo_acceso VARCHAR(32) NOT NULL,
    descripcion TEXT,
    activo BOOLEAN NOT NULL DEFAULT true,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT now(),
    fecha_actualizacion TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE lms_core.grupo_alumnos (
    id_grupo BIGINT NOT NULL REFERENCES lms_core.grupos_docente(id_grupo) ON DELETE CASCADE,
    id_alumno UUID NOT NULL REFERENCES lms_core.usuarios(id_usuario),
    activo BOOLEAN NOT NULL DEFAULT true,
    fecha_asignacion TIMESTAMP NOT NULL DEFAULT now(),
    PRIMARY KEY (id_grupo, id_alumno)
);

CREATE TABLE lms_core.ejercicios_practicos (
    id_ejercicio integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_modulo integer REFERENCES lms_core.modulos(id_modulo) ON DELETE CASCADE,
    enunciado text NOT NULL,
    query_maestra text NOT NULL,
    dificultad integer NOT NULL,
    configuracion_extra jsonb,
    titulo text NOT NULL DEFAULT 'Mision Desconocida',
    orden integer NOT NULL DEFAULT 1,
    tipo_mision text NOT NULL DEFAULT 'HISTORIA',
    formato character varying(50) NOT NULL DEFAULT 'editor',
    creado_por UUID REFERENCES lms_core.usuarios(id_usuario),
    visibilidad VARCHAR(20) NOT NULL DEFAULT 'GLOBAL',
    id_grupo BIGINT REFERENCES lms_core.grupos_docente(id_grupo),
    CONSTRAINT ejercicios_practicos_dificultad_check CHECK (dificultad BETWEEN 1 AND 5),
    CONSTRAINT ejercicios_practicos_orden_check CHECK (orden > 0),
    CONSTRAINT ejercicios_practicos_tipo_mision_check CHECK (tipo_mision IN ('HISTORIA', 'RAPIDA', 'DOCENTE')),
    CONSTRAINT ejercicios_practicos_formato_check CHECK (formato IN ('editor', 'sql', 'diagram', 'drag_drop')),
    CONSTRAINT chk_ejercicios_visibilidad CHECK (visibilidad IN ('GLOBAL', 'DOCENTE', 'GRUPO'))
);

CREATE TABLE lms_core.evaluaciones_docente (
    id_evaluacion BIGSERIAL PRIMARY KEY,
    id_docente UUID NOT NULL REFERENCES lms_core.usuarios(id_usuario),
    id_alumno UUID NOT NULL REFERENCES lms_core.usuarios(id_usuario),
    id_curso INT REFERENCES lms_core.cursos(id_curso),
    id_modulo INT REFERENCES lms_core.modulos(id_modulo),
    calificacion NUMERIC(4,2) NOT NULL CHECK (calificacion >= 0 AND calificacion <= 10),
    comentario TEXT,
    fecha_evaluacion TIMESTAMP NOT NULL DEFAULT now(),
    UNIQUE (id_docente, id_alumno, id_modulo)
);

CREATE TABLE lms_core.clawbot_cache (
    clave       char(64)    PRIMARY KEY,
    respuesta   text        NOT NULL,
    fuente      varchar(40) NOT NULL,
    aciertos    integer     NOT NULL DEFAULT 0,
    creado_en   timestamptz NOT NULL DEFAULT now(),
    ultimo_uso  timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE lms_core.clawbot_cache IS
    'Respuestas de Clawbot ya pagadas. aciertos = veces que se sirvio sin llamar a la IA.';

CREATE TABLE lms_core.intentos (
    id_intento uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    id_usuario uuid REFERENCES lms_core.usuarios(id_usuario) ON DELETE CASCADE,
    id_ejercicio integer REFERENCES lms_core.ejercicios_practicos(id_ejercicio) ON DELETE CASCADE,
    query_enviada text NOT NULL,
    es_correcto boolean NOT NULL,
    tiempo_ms numeric(8,2),
    costo_ejecucion numeric(12,2),
    longitud_caracteres integer,
    fecha_intento timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT intentos_tiempo_ms_check CHECK (tiempo_ms IS NULL OR tiempo_ms >= 0),
    CONSTRAINT intentos_costo_ejecucion_check CHECK (costo_ejecucion IS NULL OR costo_ejecucion >= 0),
    CONSTRAINT intentos_longitud_caracteres_check CHECK (longitud_caracteres IS NULL OR longitud_caracteres >= 0)
);

CREATE TABLE lms_core.auditoria_logs (
    id_log integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tabla_afectada text,
    operacion text,
    usuario_db text,
    fecha timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    datos_antiguos jsonb,
    CONSTRAINT auditoria_logs_operacion_check CHECK (operacion IS NULL OR operacion IN ('INSERT', 'UPDATE', 'DELETE'))
);

CREATE INDEX idx_intentos_usuario_ejercicio_correcto_fecha
    ON lms_core.intentos (id_usuario, id_ejercicio, es_correcto, fecha_intento DESC);

CREATE INDEX idx_intentos_ejercicio_eficiencia
    ON lms_core.intentos (id_ejercicio, es_correcto, costo_ejecucion, tiempo_ms, fecha_intento)
    WHERE es_correcto = true;

CREATE INDEX idx_intentos_ejercicio_sql_golf
    ON lms_core.intentos (id_ejercicio, es_correcto, longitud_caracteres, costo_ejecucion, fecha_intento)
    WHERE es_correcto = true;

CREATE INDEX idx_ejercicios_modulo_orden
    ON lms_core.ejercicios_practicos (id_modulo, orden);

CREATE INDEX idx_modulos_curso_orden
    ON lms_core.modulos (id_curso, orden);

CREATE UNIQUE INDEX uq_grupos_docente_codigo_acceso
    ON lms_core.grupos_docente (UPPER(codigo_acceso));

CREATE INDEX idx_grupos_docente_docente
    ON lms_core.grupos_docente (id_docente);

CREATE INDEX idx_grupo_alumnos_alumno
    ON lms_core.grupo_alumnos (id_alumno);

CREATE INDEX idx_evaluaciones_docente_alumno
    ON lms_core.evaluaciones_docente (id_docente, id_alumno);

CREATE INDEX idx_ejercicios_visibilidad
    ON lms_core.ejercicios_practicos (visibilidad, creado_por, id_grupo);

CREATE INDEX idx_clawbot_cache_ultimo_uso
    ON lms_core.clawbot_cache (ultimo_uso);

CREATE OR REPLACE VIEW lms_core.v_contenido_modulos AS
SELECT
    m.id_modulo,
    m.titulo AS modulo_titulo,
    e.id_ejercicio,
    e.titulo AS ejercicio_titulo,
    e.dificultad,
    e.orden AS ejercicio_orden
FROM lms_core.modulos m
JOIN lms_core.ejercicios_practicos e ON m.id_modulo = e.id_modulo
ORDER BY m.orden, e.orden;

CREATE OR REPLACE VIEW lms_core.v_ranking_alumnos AS
WITH historia_unica AS (
    SELECT DISTINCT i.id_usuario, i.id_ejercicio
    FROM lms_core.intentos i
    JOIN lms_core.ejercicios_practicos e ON e.id_ejercicio = i.id_ejercicio
    WHERE i.es_correcto = true
      AND COALESCE(e.tipo_mision, 'HISTORIA') <> 'RAPIDA'
),
historia AS (
    SELECT hu.id_usuario,
           SUM(e.dificultad * 10) AS xp_historia
    FROM historia_unica hu
    JOIN lms_core.ejercicios_practicos e ON e.id_ejercicio = hu.id_ejercicio
    GROUP BY hu.id_usuario
),
rapida_ordenada AS (
    SELECT i.id_usuario,
           ROW_NUMBER() OVER (
               PARTITION BY i.id_usuario, DATE(i.fecha_intento)
               ORDER BY i.fecha_intento, i.id_intento
           ) AS rn
    FROM lms_core.intentos i
    JOIN lms_core.ejercicios_practicos e ON e.id_ejercicio = i.id_ejercicio
    WHERE i.es_correcto = true
      AND e.tipo_mision = 'RAPIDA'
),
rapida AS (
    SELECT id_usuario,
           COUNT(*) * 5 AS xp_rapida
    FROM rapida_ordenada
    WHERE rn <= 5
    GROUP BY id_usuario
),
ejercicios AS (
    SELECT id_usuario,
           COUNT(DISTINCT id_ejercicio) AS ejercicios_resueltos
    FROM lms_core.intentos
    WHERE es_correcto = true
    GROUP BY id_usuario
)
SELECT
    u.id_usuario,
    u.nombre,
    u.email,
    COALESCE(ej.ejercicios_resueltos, 0) AS ejercicios_resueltos,
    COALESCE(h.xp_historia, 0) + COALESCE(r.xp_rapida, 0) AS xp_total
FROM lms_core.usuarios u
LEFT JOIN historia h ON h.id_usuario = u.id_usuario
LEFT JOIN rapida r ON r.id_usuario = u.id_usuario
LEFT JOIN ejercicios ej ON ej.id_usuario = u.id_usuario
WHERE u.activo = true
ORDER BY xp_total DESC, ejercicios_resueltos DESC, u.nombre;

-- XP por materia: misma formula que v_ranking_alumnos (historia unica + practica
-- rapida con tope de 5 por dia), agrupada por cursos.materia_slug. El tope diario
-- se calcula sobre todas las materias, asi que la suma de materias = xp_total global.
CREATE OR REPLACE VIEW lms_core.v_xp_por_materia AS
WITH historia_unica AS (
    SELECT DISTINCT i.id_usuario, i.id_ejercicio
    FROM lms_core.intentos i
    JOIN lms_core.ejercicios_practicos e ON e.id_ejercicio = i.id_ejercicio
    WHERE i.es_correcto = true
      AND COALESCE(e.tipo_mision, 'HISTORIA') <> 'RAPIDA'
),
historia AS (
    SELECT hu.id_usuario,
           c.materia_slug,
           SUM(e.dificultad * 10) AS xp
    FROM historia_unica hu
    JOIN lms_core.ejercicios_practicos e ON e.id_ejercicio = hu.id_ejercicio
    JOIN lms_core.modulos m ON m.id_modulo = e.id_modulo
    JOIN lms_core.cursos c ON c.id_curso = m.id_curso
    GROUP BY hu.id_usuario, c.materia_slug
),
rapida_ordenada AS (
    SELECT i.id_usuario,
           c.materia_slug,
           ROW_NUMBER() OVER (
               PARTITION BY i.id_usuario, DATE(i.fecha_intento)
               ORDER BY i.fecha_intento, i.id_intento
           ) AS rn
    FROM lms_core.intentos i
    JOIN lms_core.ejercicios_practicos e ON e.id_ejercicio = i.id_ejercicio
    JOIN lms_core.modulos m ON m.id_modulo = e.id_modulo
    JOIN lms_core.cursos c ON c.id_curso = m.id_curso
    WHERE i.es_correcto = true
      AND e.tipo_mision = 'RAPIDA'
),
rapida AS (
    SELECT id_usuario,
           materia_slug,
           COUNT(*) * 5 AS xp
    FROM rapida_ordenada
    WHERE rn <= 5
    GROUP BY id_usuario, materia_slug
),
xp_materia AS (
    SELECT id_usuario, materia_slug, SUM(xp)::bigint AS xp
    FROM (
        SELECT id_usuario, materia_slug, xp FROM historia
        UNION ALL
        SELECT id_usuario, materia_slug, xp FROM rapida
    ) t
    GROUP BY id_usuario, materia_slug
),
ejercicios AS (
    SELECT i.id_usuario,
           c.materia_slug,
           COUNT(DISTINCT i.id_ejercicio) AS ejercicios_resueltos
    FROM lms_core.intentos i
    JOIN lms_core.ejercicios_practicos e ON e.id_ejercicio = i.id_ejercicio
    JOIN lms_core.modulos m ON m.id_modulo = e.id_modulo
    JOIN lms_core.cursos c ON c.id_curso = m.id_curso
    WHERE i.es_correcto = true
    GROUP BY i.id_usuario, c.materia_slug
)
SELECT x.id_usuario,
       x.materia_slug,
       x.xp,
       COALESCE(ej.ejercicios_resueltos, 0) AS ejercicios_resueltos
FROM xp_materia x
JOIN lms_core.usuarios u ON u.id_usuario = x.id_usuario AND u.activo = true
LEFT JOIN ejercicios ej ON ej.id_usuario = x.id_usuario AND ej.materia_slug = x.materia_slug;
CREATE OR REPLACE FUNCTION lms_core.fn_auditar_ejercicios()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO lms_core.auditoria_logs (tabla_afectada, operacion, usuario_db, datos_antiguos)
    VALUES (TG_TABLE_NAME, TG_OP, current_user, row_to_json(OLD));
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION lms_core.fn_crear_multiverso()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    nuevo_esquema text;
    tabla record;
BEGIN
    nuevo_esquema := 'sandbox_usuario_' || NEW.id_usuario;

    EXECUTE format('CREATE SCHEMA %I', nuevo_esquema);
    EXECUTE format('ALTER SCHEMA %I OWNER TO app_sandbox_user', nuevo_esquema);

    FOR tabla IN
        SELECT tablename FROM pg_tables WHERE schemaname = 'lms_sandbox_template'
    LOOP
        EXECUTE format('CREATE TABLE %I.%I (LIKE lms_sandbox_template.%I INCLUDING ALL)', nuevo_esquema, tabla.tablename, tabla.tablename);
        EXECUTE format('INSERT INTO %I.%I SELECT * FROM lms_sandbox_template.%I', nuevo_esquema, tabla.tablename, tabla.tablename);
        EXECUTE format('ALTER TABLE %I.%I OWNER TO app_sandbox_user', nuevo_esquema, tabla.tablename);
    END LOOP;

    RETURN NEW;
END;
$$;

CREATE RULE regla_soft_delete_usuarios AS
    ON DELETE TO lms_core.usuarios
    DO INSTEAD
    UPDATE lms_core.usuarios
       SET activo = false
     WHERE usuarios.id_usuario = OLD.id_usuario;

CREATE TRIGGER trg_auditar_update_ejercicio
AFTER UPDATE ON lms_core.ejercicios_practicos
FOR EACH ROW
WHEN (OLD.query_maestra IS DISTINCT FROM NEW.query_maestra)
EXECUTE FUNCTION lms_core.fn_auditar_ejercicios();

CREATE TRIGGER trg_desatar_multiverso
AFTER INSERT ON lms_core.usuarios
FOR EACH ROW
EXECUTE FUNCTION lms_core.fn_crear_multiverso();

CREATE TABLE lms_sandbox_template.aventureros (
    id_aventurero integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre text,
    clase text,
    nivel integer
);

CREATE TABLE lms_sandbox_template.equipamiento (
    id_equipo integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_aventurero integer,
    item text,
    precio integer
);

CREATE TABLE lms_sandbox_template.habitaciones (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero integer,
    tipo character varying(50),
    precio_noche numeric(10,2)
);

CREATE TABLE lms_sandbox_template.huespedes (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre character varying(100),
    nivel_aventurero integer
);

CREATE TABLE lms_sandbox_template.reservas (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_entrada date DEFAULT CURRENT_DATE,
    id_huesped integer REFERENCES lms_sandbox_template.huespedes(id),
    id_habitacion integer REFERENCES lms_sandbox_template.habitaciones(id)
);

CREATE TABLE lms_sandbox.aventureros (
    id_aventurero integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre text,
    clase text,
    nivel integer
);

CREATE TABLE lms_sandbox.equipamiento (
    id_equipo integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_aventurero integer,
    item text,
    precio integer
);

CREATE TABLE lms_sandbox.habitaciones (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero integer,
    tipo character varying(50),
    precio_noche numeric(10,2)
);

CREATE TABLE lms_sandbox.huespedes (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre character varying(100),
    nivel_aventurero integer
);

CREATE TABLE lms_sandbox.reservas (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_entrada date DEFAULT CURRENT_DATE,
    id_huesped integer REFERENCES lms_sandbox.huespedes(id),
    id_habitacion integer REFERENCES lms_sandbox.habitaciones(id)
);

GRANT USAGE ON SCHEMA lms_core TO app_backend_user;
GRANT USAGE ON SCHEMA lms_sandbox TO app_backend_user;
GRANT USAGE ON SCHEMA lms_sandbox TO app_sandbox_user;
GRANT USAGE ON SCHEMA lms_sandbox_template TO app_backend_user;
GRANT USAGE ON SCHEMA lms_sandbox_template TO app_sandbox_user;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA lms_core TO app_backend_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA lms_core TO app_backend_user;
GRANT SELECT ON lms_core.v_ranking_alumnos TO app_backend_user;
GRANT SELECT ON lms_core.v_contenido_modulos TO app_backend_user;
GRANT SELECT ON lms_core.v_xp_por_materia TO app_backend_user;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA lms_sandbox_template TO app_sandbox_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA lms_sandbox_template TO app_sandbox_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA lms_sandbox TO app_sandbox_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA lms_sandbox TO app_sandbox_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA lms_sandbox_template
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_sandbox_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA lms_sandbox_template
GRANT USAGE, SELECT ON SEQUENCES TO app_sandbox_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA lms_sandbox
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_sandbox_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA lms_sandbox
GRANT USAGE, SELECT ON SEQUENCES TO app_sandbox_user;


-- Provisionamiento de sandboxes con privilegios mínimos (2026-10-05).
-- Ejecutar como administrador, únicamente en la BD seleccionada explícitamente.
-- El backend puede registrar/restaurar sandboxes sin CREATE DATABASE ni SET ROLE.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = 'app_sandbox_provisioner') THEN
        CREATE ROLE app_sandbox_provisioner NOLOGIN INHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION;
    END IF;
    EXECUTE format('GRANT CREATE ON DATABASE %I TO app_sandbox_provisioner', current_database());
END;
$$;
GRANT app_sandbox_user TO app_sandbox_provisioner;
GRANT USAGE, CREATE ON SCHEMA lms_core TO app_sandbox_provisioner;
GRANT USAGE ON SCHEMA lms_sandbox_template TO app_sandbox_provisioner;
GRANT SELECT ON ALL TABLES IN SCHEMA lms_sandbox_template TO app_sandbox_provisioner;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA lms_sandbox_template TO app_sandbox_provisioner;
GRANT SELECT (id_usuario, activo) ON lms_core.usuarios TO app_sandbox_provisioner;

CREATE OR REPLACE FUNCTION lms_core.fn_provisionar_sandbox(usuario uuid, reiniciar boolean DEFAULT false)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog
AS $$
DECLARE
    esquema text := 'sandbox_usuario_' || usuario::text;
    tabla record;
    columna record;
    secuencia text;
    maximo bigint;
BEGIN
    IF usuario IS NULL OR NOT EXISTS (
        SELECT 1 FROM lms_core.usuarios u WHERE u.id_usuario = usuario AND u.activo = true
    ) THEN
        RAISE EXCEPTION 'Usuario inexistente o inactivo' USING ERRCODE = '22023';
    END IF;
    PERFORM pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(esquema, 0));
    IF reiniciar THEN
        EXECUTE pg_catalog.format('DROP SCHEMA IF EXISTS %I CASCADE', esquema);
    END IF;
    EXECUTE pg_catalog.format('CREATE SCHEMA IF NOT EXISTS %I AUTHORIZATION app_sandbox_user', esquema);
    FOR tabla IN
        SELECT c.relname FROM pg_catalog.pg_class c
        JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = 'lms_sandbox_template' AND c.relkind = 'r'
    LOOP
        IF pg_catalog.to_regclass(pg_catalog.format('%I.%I', esquema, tabla.relname)) IS NOT NULL THEN
            CONTINUE;
        END IF;
        EXECUTE pg_catalog.format('CREATE TABLE %I.%I (LIKE lms_sandbox_template.%I INCLUDING ALL)', esquema, tabla.relname, tabla.relname);
        EXECUTE pg_catalog.format('INSERT INTO %I.%I SELECT * FROM lms_sandbox_template.%I', esquema, tabla.relname, tabla.relname);
        -- Las identidades copiadas tienen secuencia propia; continuar después de los IDs semilla.
        FOR columna IN
            SELECT a.attname FROM pg_catalog.pg_attribute a
            WHERE a.attrelid = pg_catalog.to_regclass(pg_catalog.format('%I.%I', esquema, tabla.relname))
              AND a.attidentity <> '' AND a.attnum > 0 AND NOT a.attisdropped
        LOOP
            secuencia := pg_catalog.pg_get_serial_sequence(pg_catalog.format('%I.%I', esquema, tabla.relname), columna.attname);
            EXECUTE pg_catalog.format('SELECT MAX(%I) FROM %I.%I', columna.attname, esquema, tabla.relname) INTO maximo;
            PERFORM pg_catalog.setval(secuencia::pg_catalog.regclass, COALESCE(maximo, 1), maximo IS NOT NULL);
        END LOOP;
        EXECUTE pg_catalog.format('ALTER TABLE %I.%I OWNER TO app_sandbox_user', esquema, tabla.relname);
    END LOOP;
END;
$$;
ALTER FUNCTION lms_core.fn_provisionar_sandbox(uuid, boolean) OWNER TO app_sandbox_provisioner;
REVOKE ALL ON FUNCTION lms_core.fn_provisionar_sandbox(uuid, boolean) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION lms_core.fn_provisionar_sandbox(uuid, boolean) TO app_backend_user;

CREATE OR REPLACE FUNCTION lms_core.fn_crear_multiverso()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog
AS $$
BEGIN
    PERFORM lms_core.fn_provisionar_sandbox(NEW.id_usuario, false);
    RETURN NEW;
END;
$$;
ALTER FUNCTION lms_core.fn_crear_multiverso() OWNER TO app_sandbox_provisioner;
REVOKE ALL ON FUNCTION lms_core.fn_crear_multiverso() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION lms_core.fn_crear_multiverso() TO app_backend_user;
REVOKE CREATE ON SCHEMA lms_core FROM app_sandbox_provisioner;
-- El rol sandbox no recibe USAGE ni permisos sobre lms_core.

COMMIT;
