-- Dagon - instalacion limpia de base de datos
-- Script oficial de estructura para ambientes nuevos.
--
-- Orden recomendado:
--   1. Ejecutar este archivo como usuario con permisos de creacion.
--   2. Ejecutar scripts/01_datos_semilla.sql.
--   3. Ejecutar scripts/02_ejercicios_semilla.sql.
--   4. Ejecutar scripts/migraciones/*.sql en orden cronologico.
--
-- Este archivo NO contiene usuarios reales, intentos, password_hash reales ni
-- esquemas sandbox_usuario_<uuid>. El respaldo bruto queda solo como evidencia
-- historica y no como fuente de instalacion limpia.

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE SCHEMA IF NOT EXISTS lms_core;
CREATE SCHEMA IF NOT EXISTS lms_sandbox;
CREATE SCHEMA IF NOT EXISTS lms_sandbox_template;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_backend_user') THEN
        CREATE ROLE app_backend_user LOGIN;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_sandbox_user') THEN
        CREATE ROLE app_sandbox_user LOGIN;
    END IF;
END;
$$;

CREATE DOMAIN lms_core.email_valido AS text
    CONSTRAINT email_valido_check
    CHECK (VALUE ~* '^[A-Za-z0-9._%-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$');

CREATE TABLE lms_core.roles (
    id_rol integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre text NOT NULL UNIQUE,
    CONSTRAINT roles_nombre_check CHECK (nombre IN ('alumno', 'docente', 'admin'))
);

CREATE TABLE lms_core.usuarios (
    id_usuario uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    nombre text NOT NULL,
    email lms_core.email_valido NOT NULL,
    password_hash text NOT NULL,
    id_rol integer REFERENCES lms_core.roles(id_rol) ON DELETE RESTRICT,
    activo boolean NOT NULL DEFAULT true,
    fecha_registro timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    racha_actual integer NOT NULL DEFAULT 0,
    ultima_practica date,
    mejor_racha integer NOT NULL DEFAULT 0,
    CONSTRAINT usuarios_racha_actual_check CHECK (racha_actual >= 0),
    CONSTRAINT usuarios_mejor_racha_check CHECK (mejor_racha >= 0),
    CONSTRAINT usuarios_mejor_racha_consistente_check CHECK (mejor_racha >= racha_actual OR mejor_racha = 0)
);

ALTER TABLE lms_core.usuarios
    ADD CONSTRAINT usuarios_email_key UNIQUE (email);

CREATE UNIQUE INDEX idx_usuarios_email_lower_unique
    ON lms_core.usuarios (lower(email::text));

CREATE TABLE lms_core.cursos (
    id_curso integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo text NOT NULL UNIQUE
);

CREATE TABLE lms_core.modulos (
    id_modulo integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_curso integer REFERENCES lms_core.cursos(id_curso) ON DELETE CASCADE,
    titulo text NOT NULL,
    orden integer NOT NULL,
    descripcion text,
    xp_requerida integer NOT NULL DEFAULT 0,
    objetivos jsonb NOT NULL DEFAULT '[]'::jsonb,
    prerequisitos jsonb NOT NULL DEFAULT '[]'::jsonb,
    errores_comunes jsonb NOT NULL DEFAULT '[]'::jsonb,
    cinematica_config jsonb NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT modulos_orden_check CHECK (orden > 0),
    CONSTRAINT modulos_xp_requerida_check CHECK (xp_requerida >= 0),
    CONSTRAINT modulos_objetivos_array_check CHECK (jsonb_typeof(objetivos) = 'array'),
    CONSTRAINT modulos_prerequisitos_array_check CHECK (jsonb_typeof(prerequisitos) = 'array'),
    CONSTRAINT modulos_errores_comunes_array_check CHECK (jsonb_typeof(errores_comunes) = 'array'),
    CONSTRAINT modulos_cinematica_object_check CHECK (jsonb_typeof(cinematica_config) = 'object'),
    CONSTRAINT modulos_id_curso_orden_key UNIQUE (id_curso, orden)
);

CREATE TABLE lms_core.ejercicios_practicos (
    id_ejercicio integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_modulo integer REFERENCES lms_core.modulos(id_modulo) ON DELETE CASCADE,
    enunciado text NOT NULL,
    query_maestra text NOT NULL,
    dificultad integer NOT NULL,
    configuracion_extra jsonb,
    titulo text NOT NULL DEFAULT 'Mision Desconocida',
    orden integer NOT NULL DEFAULT 1,
    tipo_mision text NOT NULL DEFAULT 'HISTORIA',
    formato character varying(50) NOT NULL DEFAULT 'editor',
    CONSTRAINT ejercicios_practicos_dificultad_check CHECK (dificultad BETWEEN 1 AND 5),
    CONSTRAINT ejercicios_practicos_orden_check CHECK (orden > 0),
    CONSTRAINT ejercicios_practicos_tipo_mision_check CHECK (tipo_mision IN ('HISTORIA', 'RAPIDA')),
    CONSTRAINT ejercicios_practicos_formato_check CHECK (formato IN ('editor', 'sql', 'diagram', 'drag_drop'))
);

CREATE TABLE lms_core.intentos (
    id_intento uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    id_usuario uuid REFERENCES lms_core.usuarios(id_usuario) ON DELETE CASCADE,
    id_ejercicio integer REFERENCES lms_core.ejercicios_practicos(id_ejercicio) ON DELETE CASCADE,
    query_enviada text NOT NULL,
    es_correcto boolean NOT NULL,
    tiempo_ms numeric(8,2),
    fecha_intento timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT intentos_tiempo_ms_check CHECK (tiempo_ms IS NULL OR tiempo_ms >= 0)
);

CREATE TABLE lms_core.auditoria_logs (
    id_log integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tabla_afectada text,
    operacion text,
    usuario_db text,
    fecha timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    datos_antiguos jsonb,
    CONSTRAINT auditoria_logs_operacion_check CHECK (operacion IS NULL OR operacion IN ('INSERT', 'UPDATE', 'DELETE'))
);

CREATE INDEX idx_intentos_usuario_ejercicio_correcto_fecha
    ON lms_core.intentos (id_usuario, id_ejercicio, es_correcto, fecha_intento DESC);

CREATE INDEX idx_ejercicios_modulo_orden
    ON lms_core.ejercicios_practicos (id_modulo, orden);

CREATE INDEX idx_modulos_curso_orden
    ON lms_core.modulos (id_curso, orden);

CREATE OR REPLACE VIEW lms_core.v_contenido_modulos AS
SELECT
    m.id_modulo,
    m.titulo AS modulo_titulo,
    e.id_ejercicio,
    e.titulo AS ejercicio_titulo,
    e.dificultad,
    e.orden AS ejercicio_orden
FROM lms_core.modulos m
JOIN lms_core.ejercicios_practicos e ON m.id_modulo = e.id_modulo
ORDER BY m.orden, e.orden;

CREATE OR REPLACE VIEW lms_core.v_ranking_alumnos AS
SELECT
    u.id_usuario,
    u.nombre,
    u.email,
    COUNT(DISTINCT i.id_ejercicio) AS ejercicios_resueltos,
    COALESCE(SUM(
        CASE
            WHEN e.tipo_mision = 'RAPIDA' THEN 5
            ELSE e.dificultad * 10
        END
    ), 0) AS xp_total
FROM lms_core.usuarios u
LEFT JOIN (
    SELECT DISTINCT id_usuario, id_ejercicio
    FROM lms_core.intentos
    WHERE es_correcto = true
) i ON u.id_usuario = i.id_usuario
LEFT JOIN lms_core.ejercicios_practicos e ON i.id_ejercicio = e.id_ejercicio
WHERE u.activo = true
GROUP BY u.id_usuario, u.nombre, u.email
ORDER BY xp_total DESC, COUNT(DISTINCT i.id_ejercicio) DESC, u.nombre;

CREATE OR REPLACE FUNCTION lms_core.fn_auditar_ejercicios()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO lms_core.auditoria_logs (tabla_afectada, operacion, usuario_db, datos_antiguos)
    VALUES (TG_TABLE_NAME, TG_OP, current_user, row_to_json(OLD));
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION lms_core.fn_crear_multiverso()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    nuevo_esquema text;
    tabla record;
BEGIN
    nuevo_esquema := 'sandbox_usuario_' || NEW.id_usuario;

    EXECUTE format('CREATE SCHEMA %I', nuevo_esquema);
    EXECUTE format('ALTER SCHEMA %I OWNER TO app_sandbox_user', nuevo_esquema);

    FOR tabla IN
        SELECT tablename FROM pg_tables WHERE schemaname = 'lms_sandbox_template'
    LOOP
        EXECUTE format('CREATE TABLE %I.%I (LIKE lms_sandbox_template.%I INCLUDING ALL)', nuevo_esquema, tabla.tablename, tabla.tablename);
        EXECUTE format('INSERT INTO %I.%I SELECT * FROM lms_sandbox_template.%I', nuevo_esquema, tabla.tablename, tabla.tablename);
        EXECUTE format('ALTER TABLE %I.%I OWNER TO app_sandbox_user', nuevo_esquema, tabla.tablename);
    END LOOP;

    RETURN NEW;
END;
$$;

CREATE RULE regla_soft_delete_usuarios AS
    ON DELETE TO lms_core.usuarios
    DO INSTEAD
    UPDATE lms_core.usuarios
       SET activo = false
     WHERE usuarios.id_usuario = OLD.id_usuario;

CREATE TRIGGER trg_auditar_update_ejercicio
AFTER UPDATE ON lms_core.ejercicios_practicos
FOR EACH ROW
WHEN (OLD.query_maestra IS DISTINCT FROM NEW.query_maestra)
EXECUTE FUNCTION lms_core.fn_auditar_ejercicios();

CREATE TRIGGER trg_desatar_multiverso
AFTER INSERT ON lms_core.usuarios
FOR EACH ROW
EXECUTE FUNCTION lms_core.fn_crear_multiverso();

CREATE TABLE lms_sandbox_template.aventureros (
    id_aventurero integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre text,
    clase text,
    nivel integer
);

CREATE TABLE lms_sandbox_template.equipamiento (
    id_equipo integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_aventurero integer,
    item text,
    precio integer
);

CREATE TABLE lms_sandbox_template.habitaciones (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero integer,
    tipo character varying(50),
    precio_noche numeric(10,2)
);

CREATE TABLE lms_sandbox_template.huespedes (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre character varying(100),
    nivel_aventurero integer
);

CREATE TABLE lms_sandbox_template.reservas (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_entrada date DEFAULT CURRENT_DATE,
    id_huesped integer REFERENCES lms_sandbox_template.huespedes(id),
    id_habitacion integer REFERENCES lms_sandbox_template.habitaciones(id)
);

CREATE TABLE lms_sandbox.aventureros (
    id_aventurero integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre text,
    clase text,
    nivel integer
);

CREATE TABLE lms_sandbox.equipamiento (
    id_equipo integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_aventurero integer,
    item text,
    precio integer
);

CREATE TABLE lms_sandbox.habitaciones (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero integer,
    tipo character varying(50),
    precio_noche numeric(10,2)
);

CREATE TABLE lms_sandbox.huespedes (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre character varying(100),
    nivel_aventurero integer
);

CREATE TABLE lms_sandbox.reservas (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_entrada date DEFAULT CURRENT_DATE,
    id_huesped integer REFERENCES lms_sandbox.huespedes(id),
    id_habitacion integer REFERENCES lms_sandbox.habitaciones(id)
);

GRANT USAGE ON SCHEMA lms_core TO app_backend_user;
GRANT USAGE ON SCHEMA lms_sandbox TO app_backend_user;
GRANT USAGE ON SCHEMA lms_sandbox TO app_sandbox_user;
GRANT USAGE ON SCHEMA lms_sandbox_template TO app_backend_user;
GRANT USAGE ON SCHEMA lms_sandbox_template TO app_sandbox_user;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA lms_core TO app_backend_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA lms_core TO app_backend_user;
GRANT SELECT ON lms_core.v_ranking_alumnos TO app_backend_user;
GRANT SELECT ON lms_core.v_contenido_modulos TO app_backend_user;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA lms_sandbox_template TO app_sandbox_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA lms_sandbox_template TO app_sandbox_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA lms_sandbox TO app_sandbox_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA lms_sandbox TO app_sandbox_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA lms_sandbox_template
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_sandbox_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA lms_sandbox_template
GRANT USAGE, SELECT ON SEQUENCES TO app_sandbox_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA lms_sandbox
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_sandbox_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA lms_sandbox
GRANT USAGE, SELECT ON SEQUENCES TO app_sandbox_user;

COMMIT;
