-- Contenido original IO. Requiere esquema multimateria y migración 2026_10_05_materias_io.sql.
-- Aplicar SOLO a PostgreSQL local autorizada. No se ejecuta automáticamente.
-- Idempotencia por título de curso, (curso,orden) y configuracion_extra.semilla_clave.
BEGIN;
LOCK TABLE lms_core.cursos, lms_core.modulos, lms_core.ejercicios_practicos IN SHARE ROW EXCLUSIVE MODE;
SELECT setval(pg_get_serial_sequence('lms_core.cursos','id_curso'), GREATEST(COALESCE((SELECT MAX(id_curso) FROM lms_core.cursos),0), nextval(pg_get_serial_sequence('lms_core.cursos','id_curso'))), true);
SELECT setval(pg_get_serial_sequence('lms_core.modulos','id_modulo'), GREATEST(COALESCE((SELECT MAX(id_modulo) FROM lms_core.modulos),0), nextval(pg_get_serial_sequence('lms_core.modulos','id_modulo'))), true);
SELECT setval(pg_get_serial_sequence('lms_core.ejercicios_practicos','id_ejercicio'), GREATEST(COALESCE((SELECT MAX(id_ejercicio) FROM lms_core.ejercicios_practicos),0), nextval(pg_get_serial_sequence('lms_core.ejercicios_practicos','id_ejercicio'))), true);
INSERT INTO lms_core.cursos(titulo,materia_slug) VALUES ('IO I — Programación Lineal y Redes de Distribución','io') ON CONFLICT(titulo) DO NOTHING;
INSERT INTO lms_core.cursos(titulo,materia_slug) VALUES ('IO II — Modelos Estocásticos y Proyectos','io') ON CONFLICT(titulo) DO NOTHING;
DO $semilla$
DECLARE curso_id integer; modulo_id integer; ejercicio_id integer;
BEGIN
  SELECT id_curso INTO STRICT curso_id FROM lms_core.cursos WHERE titulo='IO I — Programación Lineal y Redes de Distribución' AND materia_slug='io';
  INSERT INTO lms_core.modulos(id_curso,titulo,orden,descripcion,xp_requerida,objetivos,errores_comunes)
  VALUES(curso_id,'Introducción a la Investigación de Operaciones',1,'La IO transforma una decisión en un modelo verificable. Primero delimita el problema, obtiene datos, formula variables y restricciones, resuelve, valida con la realidad y revisa los supuestos.',0,'["Distinguir decisiones, parámetros y restricciones","Conectar un modelo con una decisión real"]'::jsonb,'["Optimizar antes de definir la decisión","Confundir pronósticos con variables controlables"]'::jsonb)
  ON CONFLICT(id_curso,orden) DO UPDATE SET titulo=EXCLUDED.titulo,descripcion=EXCLUDED.descripcion,xp_requerida=EXCLUDED.xp_requerida,objetivos=EXCLUDED.objetivos,errores_comunes=EXCLUDED.errores_comunes
  RETURNING id_modulo INTO modulo_id;
  SELECT id_ejercicio INTO ejercicio_id FROM lms_core.ejercicios_practicos WHERE id_modulo=modulo_id AND configuracion_extra->>'semilla_clave'='io-unach-v1:io-i:1:1';
  IF ejercicio_id IS NULL THEN
    INSERT INTO lms_core.ejercicios_practicos(id_modulo,titulo,enunciado,query_maestra,dificultad,configuracion_extra,orden,tipo_mision,formato,visibilidad)
    VALUES(modulo_id,'Decidir qué producir','Una fábrica elige cantidades de mesas y sillas. ¿Qué elemento representan esas cantidades?','',2,'{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-i:1:1","campos":[{"clave":"elemento","etiqueta":"Elemento","tipo":"opcion","opciones":["variable","parámetro","restricción"]}],"respuestas":{"elemento":"variable"},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-i","modulo_orden":1}'::jsonb,1,'HISTORIA','editor','GLOBAL');
  ELSE
    UPDATE lms_core.ejercicios_practicos SET titulo='Decidir qué producir',enunciado='Una fábrica elige cantidades de mesas y sillas. ¿Qué elemento representan esas cantidades?',query_maestra='',dificultad=2,configuracion_extra='{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-i:1:1","campos":[{"clave":"elemento","etiqueta":"Elemento","tipo":"opcion","opciones":["variable","parámetro","restricción"]}],"respuestas":{"elemento":"variable"},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-i","modulo_orden":1}'::jsonb,orden=1,tipo_mision='HISTORIA',formato='editor',visibilidad='GLOBAL' WHERE id_ejercicio=ejercicio_id;
  END IF;
  SELECT id_ejercicio INTO ejercicio_id FROM lms_core.ejercicios_practicos WHERE id_modulo=modulo_id AND configuracion_extra->>'semilla_clave'='io-unach-v1:io-i:1:2';
  IF ejercicio_id IS NULL THEN
    INSERT INTO lms_core.ejercicios_practicos(id_modulo,titulo,enunciado,query_maestra,dificultad,configuracion_extra,orden,tipo_mision,formato,visibilidad)
    VALUES(modulo_id,'Recurso limitado','La fábrica dispone de 40 horas de trabajo. ¿Qué parte del modelo representa ese límite?','',3,'{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-i:1:2","campos":[{"clave":"elemento","etiqueta":"Elemento","tipo":"opcion","opciones":["objetivo","restricción","solución"]}],"respuestas":{"elemento":"restricción"},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-i","modulo_orden":1}'::jsonb,2,'HISTORIA','editor','GLOBAL');
  ELSE
    UPDATE lms_core.ejercicios_practicos SET titulo='Recurso limitado',enunciado='La fábrica dispone de 40 horas de trabajo. ¿Qué parte del modelo representa ese límite?',query_maestra='',dificultad=3,configuracion_extra='{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-i:1:2","campos":[{"clave":"elemento","etiqueta":"Elemento","tipo":"opcion","opciones":["objetivo","restricción","solución"]}],"respuestas":{"elemento":"restricción"},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-i","modulo_orden":1}'::jsonb,orden=2,tipo_mision='HISTORIA',formato='editor',visibilidad='GLOBAL' WHERE id_ejercicio=ejercicio_id;
  END IF;
  SELECT id_ejercicio INTO ejercicio_id FROM lms_core.ejercicios_practicos WHERE id_modulo=modulo_id AND configuracion_extra->>'semilla_clave'='io-unach-v1:io-i:1:3';
  IF ejercicio_id IS NULL THEN
    INSERT INTO lms_core.ejercicios_practicos(id_modulo,titulo,enunciado,query_maestra,dificultad,configuracion_extra,orden,tipo_mision,formato,visibilidad)
    VALUES(modulo_id,'Validar el modelo','El solver entrega un óptimo. Antes de implementarlo, ¿qué sigue?','',4,'{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-i:1:3","campos":[{"clave":"paso","etiqueta":"Paso","tipo":"opcion","opciones":["ignorar datos","validar supuestos","eliminar restricciones"]}],"respuestas":{"paso":"validar supuestos"},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-i","modulo_orden":1}'::jsonb,3,'HISTORIA','editor','GLOBAL');
  ELSE
    UPDATE lms_core.ejercicios_practicos SET titulo='Validar el modelo',enunciado='El solver entrega un óptimo. Antes de implementarlo, ¿qué sigue?',query_maestra='',dificultad=4,configuracion_extra='{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-i:1:3","campos":[{"clave":"paso","etiqueta":"Paso","tipo":"opcion","opciones":["ignorar datos","validar supuestos","eliminar restricciones"]}],"respuestas":{"paso":"validar supuestos"},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-i","modulo_orden":1}'::jsonb,orden=3,tipo_mision='HISTORIA',formato='editor',visibilidad='GLOBAL' WHERE id_ejercicio=ejercicio_id;
  END IF;
  SELECT id_curso INTO STRICT curso_id FROM lms_core.cursos WHERE titulo='IO I — Programación Lineal y Redes de Distribución' AND materia_slug='io';
  INSERT INTO lms_core.modulos(id_curso,titulo,orden,descripcion,xp_requerida,objetivos,errores_comunes)
  VALUES(curso_id,'Formulación de modelos de programación lineal',2,'Define x1 y x2 con unidades explícitas. La contribución unitaria multiplicada por cada cantidad construye Z; el consumo unitario construye cada restricción.',30,'["Traducir recursos y ganancias a coeficientes","Declarar unidades y no negatividad"]'::jsonb,'["Cambiar unidades entre lados de una desigualdad","Invertir el sentido de un mínimo exigido"]'::jsonb)
  ON CONFLICT(id_curso,orden) DO UPDATE SET titulo=EXCLUDED.titulo,descripcion=EXCLUDED.descripcion,xp_requerida=EXCLUDED.xp_requerida,objetivos=EXCLUDED.objetivos,errores_comunes=EXCLUDED.errores_comunes
  RETURNING id_modulo INTO modulo_id;
  SELECT id_ejercicio INTO ejercicio_id FROM lms_core.ejercicios_practicos WHERE id_modulo=modulo_id AND configuracion_extra->>'semilla_clave'='io-unach-v1:io-i:2:1';
  IF ejercicio_id IS NULL THEN
    INSERT INTO lms_core.ejercicios_practicos(id_modulo,titulo,enunciado,query_maestra,dificultad,configuracion_extra,orden,tipo_mision,formato,visibilidad)
    VALUES(modulo_id,'Ganancia unitaria','Cada mesa x1 genera 3 y cada silla x2 genera 5. Escribe los coeficientes de max Z.','',2,'{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-i:2:1","campos":[{"clave":"c1","etiqueta":"C1","tipo":"numero"},{"clave":"c2","etiqueta":"C2","tipo":"numero"}],"respuestas":{"c1":3,"c2":5},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-i","modulo_orden":2}'::jsonb,1,'HISTORIA','editor','GLOBAL');
  ELSE
    UPDATE lms_core.ejercicios_practicos SET titulo='Ganancia unitaria',enunciado='Cada mesa x1 genera 3 y cada silla x2 genera 5. Escribe los coeficientes de max Z.',query_maestra='',dificultad=2,configuracion_extra='{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-i:2:1","campos":[{"clave":"c1","etiqueta":"C1","tipo":"numero"},{"clave":"c2","etiqueta":"C2","tipo":"numero"}],"respuestas":{"c1":3,"c2":5},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-i","modulo_orden":2}'::jsonb,orden=1,tipo_mision='HISTORIA',formato='editor',visibilidad='GLOBAL' WHERE id_ejercicio=ejercicio_id;
  END IF;
  SELECT id_ejercicio INTO ejercicio_id FROM lms_core.ejercicios_practicos WHERE id_modulo=modulo_id AND configuracion_extra->>'semilla_clave'='io-unach-v1:io-i:2:2';
  IF ejercicio_id IS NULL THEN
    INSERT INTO lms_core.ejercicios_practicos(id_modulo,titulo,enunciado,query_maestra,dificultad,configuracion_extra,orden,tipo_mision,formato,visibilidad)
    VALUES(modulo_id,'Horas disponibles','Cada mesa consume 3 horas y cada silla 2; hay 18 horas. Para a1*x1+a2*x2 <= b, completa los parámetros.','',3,'{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-i:2:2","campos":[{"clave":"a1","etiqueta":"A1","tipo":"numero"},{"clave":"a2","etiqueta":"A2","tipo":"numero"},{"clave":"b","etiqueta":"B","tipo":"numero"}],"respuestas":{"a1":3,"a2":2,"b":18},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-i","modulo_orden":2}'::jsonb,2,'HISTORIA','editor','GLOBAL');
  ELSE
    UPDATE lms_core.ejercicios_practicos SET titulo='Horas disponibles',enunciado='Cada mesa consume 3 horas y cada silla 2; hay 18 horas. Para a1*x1+a2*x2 <= b, completa los parámetros.',query_maestra='',dificultad=3,configuracion_extra='{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-i:2:2","campos":[{"clave":"a1","etiqueta":"A1","tipo":"numero"},{"clave":"a2","etiqueta":"A2","tipo":"numero"},{"clave":"b","etiqueta":"B","tipo":"numero"}],"respuestas":{"a1":3,"a2":2,"b":18},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-i","modulo_orden":2}'::jsonb,orden=2,tipo_mision='HISTORIA',formato='editor',visibilidad='GLOBAL' WHERE id_ejercicio=ejercicio_id;
  END IF;
  SELECT id_ejercicio INTO ejercicio_id FROM lms_core.ejercicios_practicos WHERE id_modulo=modulo_id AND configuracion_extra->>'semilla_clave'='io-unach-v1:io-i:2:3';
  IF ejercicio_id IS NULL THEN
    INSERT INTO lms_core.ejercicios_practicos(id_modulo,titulo,enunciado,query_maestra,dificultad,configuracion_extra,orden,tipo_mision,formato,visibilidad)
    VALUES(modulo_id,'Compromiso mínimo','Se requieren al menos 4 unidades totales. Elige el sentido de x1+x2 __ 4 y el límite inferior de cada variable.','',4,'{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-i:2:3","campos":[{"clave":"sentido","etiqueta":"Sentido","tipo":"opcion","opciones":["<=",">=","="]},{"clave":"inferior","etiqueta":"Inferior","tipo":"numero"}],"respuestas":{"sentido":">=","inferior":0},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-i","modulo_orden":2}'::jsonb,3,'HISTORIA','editor','GLOBAL');
  ELSE
    UPDATE lms_core.ejercicios_practicos SET titulo='Compromiso mínimo',enunciado='Se requieren al menos 4 unidades totales. Elige el sentido de x1+x2 __ 4 y el límite inferior de cada variable.',query_maestra='',dificultad=4,configuracion_extra='{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-i:2:3","campos":[{"clave":"sentido","etiqueta":"Sentido","tipo":"opcion","opciones":["<=",">=","="]},{"clave":"inferior","etiqueta":"Inferior","tipo":"numero"}],"respuestas":{"sentido":">=","inferior":0},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-i","modulo_orden":2}'::jsonb,orden=3,tipo_mision='HISTORIA',formato='editor',visibilidad='GLOBAL' WHERE id_ejercicio=ejercicio_id;
  END IF;
  SELECT id_curso INTO STRICT curso_id FROM lms_core.cursos WHERE titulo='IO I — Programación Lineal y Redes de Distribución' AND materia_slug='io';
  INSERT INTO lms_core.modulos(id_curso,titulo,orden,descripcion,xp_requerida,objetivos,errores_comunes)
  VALUES(curso_id,'Método gráfico',3,'Para dos variables dibuja las fronteras, prueba el lado factible de cada desigualdad y conserva su intersección con los ejes no negativos. Una frontera se obtiene reemplazando la desigualdad por igualdad.',60,'["Construir la región factible","Comparar el objetivo en vértices"]'::jsonb,'["Usar intersecciones que violan otra restricción","Confundir región no acotada con objetivo no acotado"]'::jsonb)
  ON CONFLICT(id_curso,orden) DO UPDATE SET titulo=EXCLUDED.titulo,descripcion=EXCLUDED.descripcion,xp_requerida=EXCLUDED.xp_requerida,objetivos=EXCLUDED.objetivos,errores_comunes=EXCLUDED.errores_comunes
  RETURNING id_modulo INTO modulo_id;
  SELECT id_ejercicio INTO ejercicio_id FROM lms_core.ejercicios_practicos WHERE id_modulo=modulo_id AND configuracion_extra->>'semilla_clave'='io-unach-v1:io-i:3:1';
  IF ejercicio_id IS NULL THEN
    INSERT INTO lms_core.ejercicios_practicos(id_modulo,titulo,enunciado,query_maestra,dificultad,configuracion_extra,orden,tipo_mision,formato,visibilidad)
    VALUES(modulo_id,'Vértice óptimo','Resuelve max Z=3x1+5x2; x1<=4, 2x2<=12, 3x1+2x2<=18; x1,x2>=0. Reporta las coordenadas óptimas.','',2,'{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-i:3:1","campos":[{"clave":"x1","etiqueta":"X1","tipo":"numero"},{"clave":"x2","etiqueta":"X2","tipo":"numero"}],"respuestas":{"x1":2,"x2":6},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-i","modulo_orden":3}'::jsonb,1,'HISTORIA','editor','GLOBAL');
  ELSE
    UPDATE lms_core.ejercicios_practicos SET titulo='Vértice óptimo',enunciado='Resuelve max Z=3x1+5x2; x1<=4, 2x2<=12, 3x1+2x2<=18; x1,x2>=0. Reporta las coordenadas óptimas.',query_maestra='',dificultad=2,configuracion_extra='{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-i:3:1","campos":[{"clave":"x1","etiqueta":"X1","tipo":"numero"},{"clave":"x2","etiqueta":"X2","tipo":"numero"}],"respuestas":{"x1":2,"x2":6},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-i","modulo_orden":3}'::jsonb,orden=1,tipo_mision='HISTORIA',formato='editor',visibilidad='GLOBAL' WHERE id_ejercicio=ejercicio_id;
  END IF;
  SELECT id_ejercicio INTO ejercicio_id FROM lms_core.ejercicios_practicos WHERE id_modulo=modulo_id AND configuracion_extra->>'semilla_clave'='io-unach-v1:io-i:3:2';
  IF ejercicio_id IS NULL THEN
    INSERT INTO lms_core.ejercicios_practicos(id_modulo,titulo,enunciado,query_maestra,dificultad,configuracion_extra,orden,tipo_mision,formato,visibilidad)
    VALUES(modulo_id,'Evaluar el objetivo','En el modelo anterior, calcula Z en el óptimo y en el vértice (4,0).','',3,'{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-i:3:2","campos":[{"clave":"z_optimo","etiqueta":"Z optimo","tipo":"numero"},{"clave":"z_40","etiqueta":"Z 40","tipo":"numero"}],"respuestas":{"z_optimo":36,"z_40":12},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-i","modulo_orden":3}'::jsonb,2,'HISTORIA','editor','GLOBAL');
  ELSE
    UPDATE lms_core.ejercicios_practicos SET titulo='Evaluar el objetivo',enunciado='En el modelo anterior, calcula Z en el óptimo y en el vértice (4,0).',query_maestra='',dificultad=3,configuracion_extra='{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-i:3:2","campos":[{"clave":"z_optimo","etiqueta":"Z optimo","tipo":"numero"},{"clave":"z_40","etiqueta":"Z 40","tipo":"numero"}],"respuestas":{"z_optimo":36,"z_40":12},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-i","modulo_orden":3}'::jsonb,orden=2,tipo_mision='HISTORIA',formato='editor',visibilidad='GLOBAL' WHERE id_ejercicio=ejercicio_id;
  END IF;
  SELECT id_ejercicio INTO ejercicio_id FROM lms_core.ejercicios_practicos WHERE id_modulo=modulo_id AND configuracion_extra->>'semilla_clave'='io-unach-v1:io-i:3:3';
  IF ejercicio_id IS NULL THEN
    INSERT INTO lms_core.ejercicios_practicos(id_modulo,titulo,enunciado,query_maestra,dificultad,configuracion_extra,orden,tipo_mision,formato,visibilidad)
    VALUES(modulo_id,'Restricción activa','En (2,6), calcula las holguras de x1<=4 y 3x1+2x2<=18.','',4,'{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-i:3:3","campos":[{"clave":"holgura_1","etiqueta":"Holgura 1","tipo":"numero"},{"clave":"holgura_3","etiqueta":"Holgura 3","tipo":"numero"}],"respuestas":{"holgura_1":2,"holgura_3":0},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-i","modulo_orden":3}'::jsonb,3,'HISTORIA','editor','GLOBAL');
  ELSE
    UPDATE lms_core.ejercicios_practicos SET titulo='Restricción activa',enunciado='En (2,6), calcula las holguras de x1<=4 y 3x1+2x2<=18.',query_maestra='',dificultad=4,configuracion_extra='{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-i:3:3","campos":[{"clave":"holgura_1","etiqueta":"Holgura 1","tipo":"numero"},{"clave":"holgura_3","etiqueta":"Holgura 3","tipo":"numero"}],"respuestas":{"holgura_1":2,"holgura_3":0},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-i","modulo_orden":3}'::jsonb,orden=3,tipo_mision='HISTORIA',formato='editor',visibilidad='GLOBAL' WHERE id_ejercicio=ejercicio_id;
  END IF;
  SELECT id_curso INTO STRICT curso_id FROM lms_core.cursos WHERE titulo='IO I — Programación Lineal y Redes de Distribución' AND materia_slug='io';
  INSERT INTO lms_core.modulos(id_curso,titulo,orden,descripcion,xp_requerida,objetivos,errores_comunes)
  VALUES(curso_id,'Simplex para maximizar',4,'Agrega holguras a restricciones <= y parte de una base factible. Los costos reducidos identifican mejoras posibles. Con un tableau que usa Zj-Cj, una entrada negativa señala mejora al maximizar.',90,'["Interpretar bases y pivotes","Comprobar factibilidad al cambiar de base"]'::jsonb,'["Dividir por coeficientes negativos en el test de cocientes","Mezclar Cj-Zj y Zj-Cj"]'::jsonb)
  ON CONFLICT(id_curso,orden) DO UPDATE SET titulo=EXCLUDED.titulo,descripcion=EXCLUDED.descripcion,xp_requerida=EXCLUDED.xp_requerida,objetivos=EXCLUDED.objetivos,errores_comunes=EXCLUDED.errores_comunes
  RETURNING id_modulo INTO modulo_id;
  SELECT id_ejercicio INTO ejercicio_id FROM lms_core.ejercicios_practicos WHERE id_modulo=modulo_id AND configuracion_extra->>'semilla_clave'='io-unach-v1:io-i:4:1';
  IF ejercicio_id IS NULL THEN
    INSERT INTO lms_core.ejercicios_practicos(id_modulo,titulo,enunciado,query_maestra,dificultad,configuracion_extra,orden,tipo_mision,formato,visibilidad)
    VALUES(modulo_id,'Primer pivote con Bland','Para Wyndor max 3x1+5x2; x1<=4, 2x2<=12, 3x1+2x2<=18, usa Bland: entra la variable de menor índice que mejora. ¿Qué variable entra y qué fila sale (filas desde 1)?','',2,'{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-i:4:1","campos":[{"clave":"entra","etiqueta":"Entra","tipo":"opcion","opciones":["x1","x2"]},{"clave":"fila_sale","etiqueta":"Fila sale","tipo":"numero"}],"respuestas":{"entra":"x1","fila_sale":1},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-i","modulo_orden":4}'::jsonb,1,'HISTORIA','editor','GLOBAL');
  ELSE
    UPDATE lms_core.ejercicios_practicos SET titulo='Primer pivote con Bland',enunciado='Para Wyndor max 3x1+5x2; x1<=4, 2x2<=12, 3x1+2x2<=18, usa Bland: entra la variable de menor índice que mejora. ¿Qué variable entra y qué fila sale (filas desde 1)?',query_maestra='',dificultad=2,configuracion_extra='{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-i:4:1","campos":[{"clave":"entra","etiqueta":"Entra","tipo":"opcion","opciones":["x1","x2"]},{"clave":"fila_sale","etiqueta":"Fila sale","tipo":"numero"}],"respuestas":{"entra":"x1","fila_sale":1},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-i","modulo_orden":4}'::jsonb,orden=1,tipo_mision='HISTORIA',formato='editor',visibilidad='GLOBAL' WHERE id_ejercicio=ejercicio_id;
  END IF;
  SELECT id_ejercicio INTO ejercicio_id FROM lms_core.ejercicios_practicos WHERE id_modulo=modulo_id AND configuracion_extra->>'semilla_clave'='io-unach-v1:io-i:4:2';
  IF ejercicio_id IS NULL THEN
    INSERT INTO lms_core.ejercicios_practicos(id_modulo,titulo,enunciado,query_maestra,dificultad,configuracion_extra,orden,tipo_mision,formato,visibilidad)
    VALUES(modulo_id,'Cociente mínimo','Si entra x1 al tableau inicial, los coeficientes positivos son 1 y 3 con RHS 4 y 18. Calcula ambos cocientes.','',3,'{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-i:4:2","campos":[{"clave":"cociente_1","etiqueta":"Cociente 1","tipo":"numero"},{"clave":"cociente_3","etiqueta":"Cociente 3","tipo":"numero"}],"respuestas":{"cociente_1":4,"cociente_3":6},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-i","modulo_orden":4}'::jsonb,2,'HISTORIA','editor','GLOBAL');
  ELSE
    UPDATE lms_core.ejercicios_practicos SET titulo='Cociente mínimo',enunciado='Si entra x1 al tableau inicial, los coeficientes positivos son 1 y 3 con RHS 4 y 18. Calcula ambos cocientes.',query_maestra='',dificultad=3,configuracion_extra='{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-i:4:2","campos":[{"clave":"cociente_1","etiqueta":"Cociente 1","tipo":"numero"},{"clave":"cociente_3","etiqueta":"Cociente 3","tipo":"numero"}],"respuestas":{"cociente_1":4,"cociente_3":6},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-i","modulo_orden":4}'::jsonb,orden=2,tipo_mision='HISTORIA',formato='editor',visibilidad='GLOBAL' WHERE id_ejercicio=ejercicio_id;
  END IF;
  SELECT id_ejercicio INTO ejercicio_id FROM lms_core.ejercicios_practicos WHERE id_modulo=modulo_id AND configuracion_extra->>'semilla_clave'='io-unach-v1:io-i:4:3';
  IF ejercicio_id IS NULL THEN
    INSERT INTO lms_core.ejercicios_practicos(id_modulo,titulo,enunciado,query_maestra,dificultad,configuracion_extra,orden,tipo_mision,formato,visibilidad)
    VALUES(modulo_id,'Leer la base final','Resuelve Wyndor por simplex y reporta x1, x2 y Z.','',4,'{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-i:4:3","campos":[{"clave":"x1","etiqueta":"X1","tipo":"numero"},{"clave":"x2","etiqueta":"X2","tipo":"numero"},{"clave":"z","etiqueta":"Z","tipo":"numero"}],"respuestas":{"x1":2,"x2":6,"z":36},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-i","modulo_orden":4}'::jsonb,3,'HISTORIA','editor','GLOBAL');
  ELSE
    UPDATE lms_core.ejercicios_practicos SET titulo='Leer la base final',enunciado='Resuelve Wyndor por simplex y reporta x1, x2 y Z.',query_maestra='',dificultad=4,configuracion_extra='{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-i:4:3","campos":[{"clave":"x1","etiqueta":"X1","tipo":"numero"},{"clave":"x2","etiqueta":"X2","tipo":"numero"},{"clave":"z","etiqueta":"Z","tipo":"numero"}],"respuestas":{"x1":2,"x2":6,"z":36},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-i","modulo_orden":4}'::jsonb,orden=3,tipo_mision='HISTORIA',formato='editor',visibilidad='GLOBAL' WHERE id_ejercicio=ejercicio_id;
  END IF;
  SELECT id_curso INTO STRICT curso_id FROM lms_core.cursos WHERE titulo='IO I — Programación Lineal y Redes de Distribución' AND materia_slug='io';
  INSERT INTO lms_core.modulos(id_curso,titulo,orden,descripcion,xp_requerida,objetivos,errores_comunes)
  VALUES(curso_id,'Minimización y variables artificiales',5,'Una restricción >= se vuelve igualdad restando un excedente; una artificial permite construir una base inicial. Las igualdades también pueden requerir artificiales.',120,'["Distinguir excedentes de artificiales","Detectar infactibilidad con Gran M"]'::jsonb,'["Sumar una holgura a una desigualdad >=","Aceptar como factible una artificial positiva"]'::jsonb)
  ON CONFLICT(id_curso,orden) DO UPDATE SET titulo=EXCLUDED.titulo,descripcion=EXCLUDED.descripcion,xp_requerida=EXCLUDED.xp_requerida,objetivos=EXCLUDED.objetivos,errores_comunes=EXCLUDED.errores_comunes
  RETURNING id_modulo INTO modulo_id;
  SELECT id_ejercicio INTO ejercicio_id FROM lms_core.ejercicios_practicos WHERE id_modulo=modulo_id AND configuracion_extra->>'semilla_clave'='io-unach-v1:io-i:5:1';
  IF ejercicio_id IS NULL THEN
    INSERT INTO lms_core.ejercicios_practicos(id_modulo,titulo,enunciado,query_maestra,dificultad,configuracion_extra,orden,tipo_mision,formato,visibilidad)
    VALUES(modulo_id,'Solución mínima','Min Z=2x+3y; x+y>=4, x+3y>=6; x,y>=0. Calcula x,y.','',2,'{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-i:5:1","campos":[{"clave":"x","etiqueta":"X","tipo":"numero"},{"clave":"y","etiqueta":"Y","tipo":"numero"}],"respuestas":{"x":3,"y":1},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-i","modulo_orden":5}'::jsonb,1,'HISTORIA','editor','GLOBAL');
  ELSE
    UPDATE lms_core.ejercicios_practicos SET titulo='Solución mínima',enunciado='Min Z=2x+3y; x+y>=4, x+3y>=6; x,y>=0. Calcula x,y.',query_maestra='',dificultad=2,configuracion_extra='{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-i:5:1","campos":[{"clave":"x","etiqueta":"X","tipo":"numero"},{"clave":"y","etiqueta":"Y","tipo":"numero"}],"respuestas":{"x":3,"y":1},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-i","modulo_orden":5}'::jsonb,orden=1,tipo_mision='HISTORIA',formato='editor',visibilidad='GLOBAL' WHERE id_ejercicio=ejercicio_id;
  END IF;
  SELECT id_ejercicio INTO ejercicio_id FROM lms_core.ejercicios_practicos WHERE id_modulo=modulo_id AND configuracion_extra->>'semilla_clave'='io-unach-v1:io-i:5:2';
  IF ejercicio_id IS NULL THEN
    INSERT INTO lms_core.ejercicios_practicos(id_modulo,titulo,enunciado,query_maestra,dificultad,configuracion_extra,orden,tipo_mision,formato,visibilidad)
    VALUES(modulo_id,'Costo y residuo','Para el modelo anterior calcula el costo mínimo y la suma x+y.','',3,'{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-i:5:2","campos":[{"clave":"z","etiqueta":"Z","tipo":"numero"},{"clave":"suma","etiqueta":"Suma","tipo":"numero"}],"respuestas":{"z":9,"suma":4},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-i","modulo_orden":5}'::jsonb,2,'HISTORIA','editor','GLOBAL');
  ELSE
    UPDATE lms_core.ejercicios_practicos SET titulo='Costo y residuo',enunciado='Para el modelo anterior calcula el costo mínimo y la suma x+y.',query_maestra='',dificultad=3,configuracion_extra='{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-i:5:2","campos":[{"clave":"z","etiqueta":"Z","tipo":"numero"},{"clave":"suma","etiqueta":"Suma","tipo":"numero"}],"respuestas":{"z":9,"suma":4},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-i","modulo_orden":5}'::jsonb,orden=2,tipo_mision='HISTORIA',formato='editor',visibilidad='GLOBAL' WHERE id_ejercicio=ejercicio_id;
  END IF;
  SELECT id_ejercicio INTO ejercicio_id FROM lms_core.ejercicios_practicos WHERE id_modulo=modulo_id AND configuracion_extra->>'semilla_clave'='io-unach-v1:io-i:5:3';
  IF ejercicio_id IS NULL THEN
    INSERT INTO lms_core.ejercicios_practicos(id_modulo,titulo,enunciado,query_maestra,dificultad,configuracion_extra,orden,tipo_mision,formato,visibilidad)
    VALUES(modulo_id,'Diagnosticar artificiales','Una artificial vale 2 al final del procedimiento correcto. ¿Qué indica?','',4,'{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-i:5:3","campos":[{"clave":"estado","etiqueta":"Estado","tipo":"opcion","opciones":["óptimo","infactible","múltiple"]}],"respuestas":{"estado":"infactible"},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-i","modulo_orden":5}'::jsonb,3,'HISTORIA','editor','GLOBAL');
  ELSE
    UPDATE lms_core.ejercicios_practicos SET titulo='Diagnosticar artificiales',enunciado='Una artificial vale 2 al final del procedimiento correcto. ¿Qué indica?',query_maestra='',dificultad=4,configuracion_extra='{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-i:5:3","campos":[{"clave":"estado","etiqueta":"Estado","tipo":"opcion","opciones":["óptimo","infactible","múltiple"]}],"respuestas":{"estado":"infactible"},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-i","modulo_orden":5}'::jsonb,orden=3,tipo_mision='HISTORIA',formato='editor',visibilidad='GLOBAL' WHERE id_ejercicio=ejercicio_id;
  END IF;
  SELECT id_curso INTO STRICT curso_id FROM lms_core.cursos WHERE titulo='IO I — Programación Lineal y Redes de Distribución' AND materia_slug='io';
  INSERT INTO lms_core.modulos(id_curso,titulo,orden,descripcion,xp_requerida,objetivos,errores_comunes)
  VALUES(curso_id,'Dualidad y sensibilidad',6,'El dual de max c^T x con Ax<=b, x>=0 es min b^T y con A^T y>=c, y>=0. Bajo optimalidad factible, ambos objetivos coinciden. La complementariedad vincula holguras y variables duales.',150,'["Interpretar precios sombra","Respetar los rangos de validez de una base"]'::jsonb,'["Aplicar precios sombra fuera de su rango","Suponer que todo recurso tiene precio sombra positivo"]'::jsonb)
  ON CONFLICT(id_curso,orden) DO UPDATE SET titulo=EXCLUDED.titulo,descripcion=EXCLUDED.descripcion,xp_requerida=EXCLUDED.xp_requerida,objetivos=EXCLUDED.objetivos,errores_comunes=EXCLUDED.errores_comunes
  RETURNING id_modulo INTO modulo_id;
  SELECT id_ejercicio INTO ejercicio_id FROM lms_core.ejercicios_practicos WHERE id_modulo=modulo_id AND configuracion_extra->>'semilla_clave'='io-unach-v1:io-i:6:1';
  IF ejercicio_id IS NULL THEN
    INSERT INTO lms_core.ejercicios_practicos(id_modulo,titulo,enunciado,query_maestra,dificultad,configuracion_extra,orden,tipo_mision,formato,visibilidad)
    VALUES(modulo_id,'Precios sombra','Resuelve Wyndor y reporta los duales correspondientes a x1<=4, 2x2<=12 y 3x1+2x2<=18.','',2,'{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-i:6:1","campos":[{"clave":"y1","etiqueta":"Y1","tipo":"numero"},{"clave":"y2","etiqueta":"Y2","tipo":"numero"},{"clave":"y3","etiqueta":"Y3","tipo":"numero"}],"respuestas":{"y1":0,"y2":1.5,"y3":1},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-i","modulo_orden":6}'::jsonb,1,'HISTORIA','editor','GLOBAL');
  ELSE
    UPDATE lms_core.ejercicios_practicos SET titulo='Precios sombra',enunciado='Resuelve Wyndor y reporta los duales correspondientes a x1<=4, 2x2<=12 y 3x1+2x2<=18.',query_maestra='',dificultad=2,configuracion_extra='{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-i:6:1","campos":[{"clave":"y1","etiqueta":"Y1","tipo":"numero"},{"clave":"y2","etiqueta":"Y2","tipo":"numero"},{"clave":"y3","etiqueta":"Y3","tipo":"numero"}],"respuestas":{"y1":0,"y2":1.5,"y3":1},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-i","modulo_orden":6}'::jsonb,orden=1,tipo_mision='HISTORIA',formato='editor',visibilidad='GLOBAL' WHERE id_ejercicio=ejercicio_id;
  END IF;
  SELECT id_ejercicio INTO ejercicio_id FROM lms_core.ejercicios_practicos WHERE id_modulo=modulo_id AND configuracion_extra->>'semilla_clave'='io-unach-v1:io-i:6:2';
  IF ejercicio_id IS NULL THEN
    INSERT INTO lms_core.ejercicios_practicos(id_modulo,titulo,enunciado,query_maestra,dificultad,configuracion_extra,orden,tipo_mision,formato,visibilidad)
    VALUES(modulo_id,'Un recurso adicional','Aumenta solo el RHS de 2x2<=12 a 13. Conservando la base, calcula el incremento y nuevo Z.','',3,'{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-i:6:2","campos":[{"clave":"incremento","etiqueta":"Incremento","tipo":"numero"},{"clave":"z","etiqueta":"Z","tipo":"numero"}],"respuestas":{"incremento":1.5,"z":37.5},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-i","modulo_orden":6}'::jsonb,2,'HISTORIA','editor','GLOBAL');
  ELSE
    UPDATE lms_core.ejercicios_practicos SET titulo='Un recurso adicional',enunciado='Aumenta solo el RHS de 2x2<=12 a 13. Conservando la base, calcula el incremento y nuevo Z.',query_maestra='',dificultad=3,configuracion_extra='{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-i:6:2","campos":[{"clave":"incremento","etiqueta":"Incremento","tipo":"numero"},{"clave":"z","etiqueta":"Z","tipo":"numero"}],"respuestas":{"incremento":1.5,"z":37.5},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-i","modulo_orden":6}'::jsonb,orden=2,tipo_mision='HISTORIA',formato='editor',visibilidad='GLOBAL' WHERE id_ejercicio=ejercicio_id;
  END IF;
  SELECT id_ejercicio INTO ejercicio_id FROM lms_core.ejercicios_practicos WHERE id_modulo=modulo_id AND configuracion_extra->>'semilla_clave'='io-unach-v1:io-i:6:3';
  IF ejercicio_id IS NULL THEN
    INSERT INTO lms_core.ejercicios_practicos(id_modulo,titulo,enunciado,query_maestra,dificultad,configuracion_extra,orden,tipo_mision,formato,visibilidad)
    VALUES(modulo_id,'Intervalo de sensibilidad','En Wyndor, ¿entre qué valores puede variar solo el RHS 12 de la segunda restricción conservando la base?','',4,'{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-i:6:3","campos":[{"clave":"minimo","etiqueta":"Minimo","tipo":"numero"},{"clave":"maximo","etiqueta":"Maximo","tipo":"numero"}],"respuestas":{"minimo":6,"maximo":18},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-i","modulo_orden":6}'::jsonb,3,'HISTORIA','editor','GLOBAL');
  ELSE
    UPDATE lms_core.ejercicios_practicos SET titulo='Intervalo de sensibilidad',enunciado='En Wyndor, ¿entre qué valores puede variar solo el RHS 12 de la segunda restricción conservando la base?',query_maestra='',dificultad=4,configuracion_extra='{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-i:6:3","campos":[{"clave":"minimo","etiqueta":"Minimo","tipo":"numero"},{"clave":"maximo","etiqueta":"Maximo","tipo":"numero"}],"respuestas":{"minimo":6,"maximo":18},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-i","modulo_orden":6}'::jsonb,orden=3,tipo_mision='HISTORIA',formato='editor',visibilidad='GLOBAL' WHERE id_ejercicio=ejercicio_id;
  END IF;
  SELECT id_curso INTO STRICT curso_id FROM lms_core.cursos WHERE titulo='IO I — Programación Lineal y Redes de Distribución' AND materia_slug='io';
  INSERT INTO lms_core.modulos(id_curso,titulo,orden,descripcion,xp_requerida,objetivos,errores_comunes)
  VALUES(curso_id,'Transporte: soluciones iniciales y MODI',7,'Una matriz de transporte conecta ofertas por fila con demandas por columna. Si los totales difieren, incorpora un origen o destino ficticio; costo cero supone ausencia de penalización, y debe justificarse.',180,'["Balancear oferta y demanda","Distinguir costo inicial de óptimo"]'::jsonb,'["Llamar óptimo a una solución inicial","Olvidar balancear o alterar cantidades con epsilon numérico"]'::jsonb)
  ON CONFLICT(id_curso,orden) DO UPDATE SET titulo=EXCLUDED.titulo,descripcion=EXCLUDED.descripcion,xp_requerida=EXCLUDED.xp_requerida,objetivos=EXCLUDED.objetivos,errores_comunes=EXCLUDED.errores_comunes
  RETURNING id_modulo INTO modulo_id;
  SELECT id_ejercicio INTO ejercicio_id FROM lms_core.ejercicios_practicos WHERE id_modulo=modulo_id AND configuracion_extra->>'semilla_clave'='io-unach-v1:io-i:7:1';
  IF ejercicio_id IS NULL THEN
    INSERT INTO lms_core.ejercicios_practicos(id_modulo,titulo,enunciado,query_maestra,dificultad,configuracion_extra,orden,tipo_mision,formato,visibilidad)
    VALUES(modulo_id,'Balanceo','Ofertas (15,25,10) y demandas (5,15,15,15). Calcula oferta total y demanda total.','',2,'{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-i:7:1","campos":[{"clave":"oferta","etiqueta":"Oferta","tipo":"numero"},{"clave":"demanda","etiqueta":"Demanda","tipo":"numero"}],"respuestas":{"oferta":50,"demanda":50},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-i","modulo_orden":7}'::jsonb,1,'HISTORIA','editor','GLOBAL');
  ELSE
    UPDATE lms_core.ejercicios_practicos SET titulo='Balanceo',enunciado='Ofertas (15,25,10) y demandas (5,15,15,15). Calcula oferta total y demanda total.',query_maestra='',dificultad=2,configuracion_extra='{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-i:7:1","campos":[{"clave":"oferta","etiqueta":"Oferta","tipo":"numero"},{"clave":"demanda","etiqueta":"Demanda","tipo":"numero"}],"respuestas":{"oferta":50,"demanda":50},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-i","modulo_orden":7}'::jsonb,orden=1,tipo_mision='HISTORIA',formato='editor',visibilidad='GLOBAL' WHERE id_ejercicio=ejercicio_id;
  END IF;
  SELECT id_ejercicio INTO ejercicio_id FROM lms_core.ejercicios_practicos WHERE id_modulo=modulo_id AND configuracion_extra->>'semilla_clave'='io-unach-v1:io-i:7:2';
  IF ejercicio_id IS NULL THEN
    INSERT INTO lms_core.ejercicios_practicos(id_modulo,titulo,enunciado,query_maestra,dificultad,configuracion_extra,orden,tipo_mision,formato,visibilidad)
    VALUES(modulo_id,'Esquina noroeste','Costos [[10,2,20,11],[12,7,9,20],[4,14,16,18]], ofertas [15,25,10], demandas [5,15,15,15]. Calcula el costo inicial de noroeste.','',3,'{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-i:7:2","campos":[{"clave":"costo","etiqueta":"Costo","tipo":"numero"}],"respuestas":{"costo":520},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-i","modulo_orden":7}'::jsonb,2,'HISTORIA','editor','GLOBAL');
  ELSE
    UPDATE lms_core.ejercicios_practicos SET titulo='Esquina noroeste',enunciado='Costos [[10,2,20,11],[12,7,9,20],[4,14,16,18]], ofertas [15,25,10], demandas [5,15,15,15]. Calcula el costo inicial de noroeste.',query_maestra='',dificultad=3,configuracion_extra='{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-i:7:2","campos":[{"clave":"costo","etiqueta":"Costo","tipo":"numero"}],"respuestas":{"costo":520},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-i","modulo_orden":7}'::jsonb,orden=2,tipo_mision='HISTORIA',formato='editor',visibilidad='GLOBAL' WHERE id_ejercicio=ejercicio_id;
  END IF;
  SELECT id_ejercicio INTO ejercicio_id FROM lms_core.ejercicios_practicos WHERE id_modulo=modulo_id AND configuracion_extra->>'semilla_clave'='io-unach-v1:io-i:7:3';
  IF ejercicio_id IS NULL THEN
    INSERT INTO lms_core.ejercicios_practicos(id_modulo,titulo,enunciado,query_maestra,dificultad,configuracion_extra,orden,tipo_mision,formato,visibilidad)
    VALUES(modulo_id,'Vogel y MODI','Para esa misma matriz calcula costo inicial con Vogel y costo óptimo después de MODI.','',4,'{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-i:7:3","campos":[{"clave":"inicial","etiqueta":"Inicial","tipo":"numero"},{"clave":"optimo","etiqueta":"Optimo","tipo":"numero"}],"respuestas":{"inicial":475,"optimo":435},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-i","modulo_orden":7}'::jsonb,3,'HISTORIA','editor','GLOBAL');
  ELSE
    UPDATE lms_core.ejercicios_practicos SET titulo='Vogel y MODI',enunciado='Para esa misma matriz calcula costo inicial con Vogel y costo óptimo después de MODI.',query_maestra='',dificultad=4,configuracion_extra='{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-i:7:3","campos":[{"clave":"inicial","etiqueta":"Inicial","tipo":"numero"},{"clave":"optimo","etiqueta":"Optimo","tipo":"numero"}],"respuestas":{"inicial":475,"optimo":435},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-i","modulo_orden":7}'::jsonb,orden=3,tipo_mision='HISTORIA',formato='editor',visibilidad='GLOBAL' WHERE id_ejercicio=ejercicio_id;
  END IF;
  SELECT id_curso INTO STRICT curso_id FROM lms_core.cursos WHERE titulo='IO I — Programación Lineal y Redes de Distribución' AND materia_slug='io';
  INSERT INTO lms_core.modulos(id_curso,titulo,orden,descripcion,xp_requerida,objetivos,errores_comunes)
  VALUES(curso_id,'Asignación: método húngaro',8,'Una asignación selecciona una celda por trabajador y por tarea. Balancea matrices rectangulares con tareas o trabajadores ficticios. Para minimizar, reduce filas y columnas y busca ceros independientes.',210,'["Resolver asignaciones uno a uno","Transformar una maximización"]'::jsonb,'["Seleccionar dos ceros en la misma columna","Reportar el objetivo de la matriz transformada"]'::jsonb)
  ON CONFLICT(id_curso,orden) DO UPDATE SET titulo=EXCLUDED.titulo,descripcion=EXCLUDED.descripcion,xp_requerida=EXCLUDED.xp_requerida,objetivos=EXCLUDED.objetivos,errores_comunes=EXCLUDED.errores_comunes
  RETURNING id_modulo INTO modulo_id;
  SELECT id_ejercicio INTO ejercicio_id FROM lms_core.ejercicios_practicos WHERE id_modulo=modulo_id AND configuracion_extra->>'semilla_clave'='io-unach-v1:io-i:8:1';
  IF ejercicio_id IS NULL THEN
    INSERT INTO lms_core.ejercicios_practicos(id_modulo,titulo,enunciado,query_maestra,dificultad,configuracion_extra,orden,tipo_mision,formato,visibilidad)
    VALUES(modulo_id,'Asignación mínima','Dos trabajadores y dos tareas tienen costos [[4,1],[2,3]]. Calcula el costo mínimo.','',2,'{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-i:8:1","campos":[{"clave":"costo","etiqueta":"Costo","tipo":"numero"}],"respuestas":{"costo":3},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-i","modulo_orden":8}'::jsonb,1,'HISTORIA','editor','GLOBAL');
  ELSE
    UPDATE lms_core.ejercicios_practicos SET titulo='Asignación mínima',enunciado='Dos trabajadores y dos tareas tienen costos [[4,1],[2,3]]. Calcula el costo mínimo.',query_maestra='',dificultad=2,configuracion_extra='{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-i:8:1","campos":[{"clave":"costo","etiqueta":"Costo","tipo":"numero"}],"respuestas":{"costo":3},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-i","modulo_orden":8}'::jsonb,orden=1,tipo_mision='HISTORIA',formato='editor',visibilidad='GLOBAL' WHERE id_ejercicio=ejercicio_id;
  END IF;
  SELECT id_ejercicio INTO ejercicio_id FROM lms_core.ejercicios_practicos WHERE id_modulo=modulo_id AND configuracion_extra->>'semilla_clave'='io-unach-v1:io-i:8:2';
  IF ejercicio_id IS NULL THEN
    INSERT INTO lms_core.ejercicios_practicos(id_modulo,titulo,enunciado,query_maestra,dificultad,configuracion_extra,orden,tipo_mision,formato,visibilidad)
    VALUES(modulo_id,'Asignación máxima','La misma matriz [[4,1],[2,3]] ahora representa ganancias. Calcula la ganancia máxima.','',3,'{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-i:8:2","campos":[{"clave":"ganancia","etiqueta":"Ganancia","tipo":"numero"}],"respuestas":{"ganancia":7},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-i","modulo_orden":8}'::jsonb,2,'HISTORIA','editor','GLOBAL');
  ELSE
    UPDATE lms_core.ejercicios_practicos SET titulo='Asignación máxima',enunciado='La misma matriz [[4,1],[2,3]] ahora representa ganancias. Calcula la ganancia máxima.',query_maestra='',dificultad=3,configuracion_extra='{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-i:8:2","campos":[{"clave":"ganancia","etiqueta":"Ganancia","tipo":"numero"}],"respuestas":{"ganancia":7},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-i","modulo_orden":8}'::jsonb,orden=2,tipo_mision='HISTORIA',formato='editor',visibilidad='GLOBAL' WHERE id_ejercicio=ejercicio_id;
  END IF;
  SELECT id_ejercicio INTO ejercicio_id FROM lms_core.ejercicios_practicos WHERE id_modulo=modulo_id AND configuracion_extra->>'semilla_clave'='io-unach-v1:io-i:8:3';
  IF ejercicio_id IS NULL THEN
    INSERT INTO lms_core.ejercicios_practicos(id_modulo,titulo,enunciado,query_maestra,dificultad,configuracion_extra,orden,tipo_mision,formato,visibilidad)
    VALUES(modulo_id,'Transformar ganancias','Con máximo 4 en [[4,1],[2,3]], transforma max a min. Reporta d11,d12,d21,d22.','',4,'{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-i:8:3","campos":[{"clave":"d11","etiqueta":"D11","tipo":"numero"},{"clave":"d12","etiqueta":"D12","tipo":"numero"},{"clave":"d21","etiqueta":"D21","tipo":"numero"},{"clave":"d22","etiqueta":"D22","tipo":"numero"}],"respuestas":{"d11":0,"d12":3,"d21":2,"d22":1},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-i","modulo_orden":8}'::jsonb,3,'HISTORIA','editor','GLOBAL');
  ELSE
    UPDATE lms_core.ejercicios_practicos SET titulo='Transformar ganancias',enunciado='Con máximo 4 en [[4,1],[2,3]], transforma max a min. Reporta d11,d12,d21,d22.',query_maestra='',dificultad=4,configuracion_extra='{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-i:8:3","campos":[{"clave":"d11","etiqueta":"D11","tipo":"numero"},{"clave":"d12","etiqueta":"D12","tipo":"numero"},{"clave":"d21","etiqueta":"D21","tipo":"numero"},{"clave":"d22","etiqueta":"D22","tipo":"numero"}],"respuestas":{"d11":0,"d12":3,"d21":2,"d22":1},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-i","modulo_orden":8}'::jsonb,orden=3,tipo_mision='HISTORIA',formato='editor',visibilidad='GLOBAL' WHERE id_ejercicio=ejercicio_id;
  END IF;
  SELECT id_curso INTO STRICT curso_id FROM lms_core.cursos WHERE titulo='IO II — Modelos Estocásticos y Proyectos' AND materia_slug='io';
  INSERT INTO lms_core.modulos(id_curso,titulo,orden,descripcion,xp_requerida,objetivos,errores_comunes)
  VALUES(curso_id,'CPM y ruta crítica',1,'En una red sin ciclos, ES de una actividad es el máximo EF de sus predecesoras y EF=ES+t. Desde la duración del proyecto, LF es el mínimo LS de sus sucesoras y LS=LF-t.',0,'["Realizar recorridos hacia adelante y atrás","Interpretar holguras y precedencias"]'::jsonb,'["Usar el mínimo en el recorrido hacia adelante","Confundir duración de actividad con duración de proyecto"]'::jsonb)
  ON CONFLICT(id_curso,orden) DO UPDATE SET titulo=EXCLUDED.titulo,descripcion=EXCLUDED.descripcion,xp_requerida=EXCLUDED.xp_requerida,objetivos=EXCLUDED.objetivos,errores_comunes=EXCLUDED.errores_comunes
  RETURNING id_modulo INTO modulo_id;
  SELECT id_ejercicio INTO ejercicio_id FROM lms_core.ejercicios_practicos WHERE id_modulo=modulo_id AND configuracion_extra->>'semilla_clave'='io-unach-v1:io-ii:1:1';
  IF ejercicio_id IS NULL THEN
    INSERT INTO lms_core.ejercicios_practicos(id_modulo,titulo,enunciado,query_maestra,dificultad,configuracion_extra,orden,tipo_mision,formato,visibilidad)
    VALUES(modulo_id,'Proyecto secuencial','A dura 3 días y B dura 4; B depende de A. Calcula duración total y ES de B.','',2,'{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-ii:1:1","campos":[{"clave":"duracion","etiqueta":"Duracion","tipo":"numero"},{"clave":"es_b","etiqueta":"Es b","tipo":"numero"}],"respuestas":{"duracion":7,"es_b":3},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-ii","modulo_orden":1}'::jsonb,1,'HISTORIA','editor','GLOBAL');
  ELSE
    UPDATE lms_core.ejercicios_practicos SET titulo='Proyecto secuencial',enunciado='A dura 3 días y B dura 4; B depende de A. Calcula duración total y ES de B.',query_maestra='',dificultad=2,configuracion_extra='{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-ii:1:1","campos":[{"clave":"duracion","etiqueta":"Duracion","tipo":"numero"},{"clave":"es_b","etiqueta":"Es b","tipo":"numero"}],"respuestas":{"duracion":7,"es_b":3},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-ii","modulo_orden":1}'::jsonb,orden=1,tipo_mision='HISTORIA',formato='editor',visibilidad='GLOBAL' WHERE id_ejercicio=ejercicio_id;
  END IF;
  SELECT id_ejercicio INTO ejercicio_id FROM lms_core.ejercicios_practicos WHERE id_modulo=modulo_id AND configuracion_extra->>'semilla_clave'='io-unach-v1:io-ii:1:2';
  IF ejercicio_id IS NULL THEN
    INSERT INTO lms_core.ejercicios_practicos(id_modulo,titulo,enunciado,query_maestra,dificultad,configuracion_extra,orden,tipo_mision,formato,visibilidad)
    VALUES(modulo_id,'Ramas paralelas','A(3) precede a B(4) y C(2); D(1) depende de B y C. Calcula duración y holgura de C.','',3,'{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-ii:1:2","campos":[{"clave":"duracion","etiqueta":"Duracion","tipo":"numero"},{"clave":"holgura_c","etiqueta":"Holgura c","tipo":"numero"}],"respuestas":{"duracion":8,"holgura_c":2},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-ii","modulo_orden":1}'::jsonb,2,'HISTORIA','editor','GLOBAL');
  ELSE
    UPDATE lms_core.ejercicios_practicos SET titulo='Ramas paralelas',enunciado='A(3) precede a B(4) y C(2); D(1) depende de B y C. Calcula duración y holgura de C.',query_maestra='',dificultad=3,configuracion_extra='{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-ii:1:2","campos":[{"clave":"duracion","etiqueta":"Duracion","tipo":"numero"},{"clave":"holgura_c","etiqueta":"Holgura c","tipo":"numero"}],"respuestas":{"duracion":8,"holgura_c":2},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-ii","modulo_orden":1}'::jsonb,orden=2,tipo_mision='HISTORIA',formato='editor',visibilidad='GLOBAL' WHERE id_ejercicio=ejercicio_id;
  END IF;
  SELECT id_ejercicio INTO ejercicio_id FROM lms_core.ejercicios_practicos WHERE id_modulo=modulo_id AND configuracion_extra->>'semilla_clave'='io-unach-v1:io-ii:1:3';
  IF ejercicio_id IS NULL THEN
    INSERT INTO lms_core.ejercicios_practicos(id_modulo,titulo,enunciado,query_maestra,dificultad,configuracion_extra,orden,tipo_mision,formato,visibilidad)
    VALUES(modulo_id,'Ruta crítica','Para esa red A->B,C->D identifica la ruta crítica.','',4,'{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-ii:1:3","campos":[{"clave":"ruta","etiqueta":"Ruta","tipo":"opcion","opciones":["A-B-D","A-C-D","B-C-D"]}],"respuestas":{"ruta":"A-B-D"},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-ii","modulo_orden":1}'::jsonb,3,'HISTORIA','editor','GLOBAL');
  ELSE
    UPDATE lms_core.ejercicios_practicos SET titulo='Ruta crítica',enunciado='Para esa red A->B,C->D identifica la ruta crítica.',query_maestra='',dificultad=4,configuracion_extra='{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-ii:1:3","campos":[{"clave":"ruta","etiqueta":"Ruta","tipo":"opcion","opciones":["A-B-D","A-C-D","B-C-D"]}],"respuestas":{"ruta":"A-B-D"},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-ii","modulo_orden":1}'::jsonb,orden=3,tipo_mision='HISTORIA',formato='editor',visibilidad='GLOBAL' WHERE id_ejercicio=ejercicio_id;
  END IF;
  SELECT id_curso INTO STRICT curso_id FROM lms_core.cursos WHERE titulo='IO II — Modelos Estocásticos y Proyectos' AND materia_slug='io';
  INSERT INTO lms_core.modulos(id_curso,titulo,orden,descripcion,xp_requerida,objetivos,errores_comunes)
  VALUES(curso_id,'PERT y probabilidad de terminación',2,'PERT resume tiempos optimista a, más probable m y pesimista b, con a<=m<=b. El tiempo esperado pesa cuatro veces m; la varianza depende del rango.',30,'["Calcular duración esperada y varianza","Entender la aproximación normal"]'::jsonb,'["Sumar desviaciones en lugar de varianzas","Confundir probabilidad con certeza contractual"]'::jsonb)
  ON CONFLICT(id_curso,orden) DO UPDATE SET titulo=EXCLUDED.titulo,descripcion=EXCLUDED.descripcion,xp_requerida=EXCLUDED.xp_requerida,objetivos=EXCLUDED.objetivos,errores_comunes=EXCLUDED.errores_comunes
  RETURNING id_modulo INTO modulo_id;
  SELECT id_ejercicio INTO ejercicio_id FROM lms_core.ejercicios_practicos WHERE id_modulo=modulo_id AND configuracion_extra->>'semilla_clave'='io-unach-v1:io-ii:2:1';
  IF ejercicio_id IS NULL THEN
    INSERT INTO lms_core.ejercicios_practicos(id_modulo,titulo,enunciado,query_maestra,dificultad,configuracion_extra,orden,tipo_mision,formato,visibilidad)
    VALUES(modulo_id,'Tiempo esperado','A tiene a=1,m=2,b=3. Calcula te y varianza.','',2,'{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-ii:2:1","campos":[{"clave":"te","etiqueta":"Te","tipo":"numero"},{"clave":"varianza","etiqueta":"Varianza","tipo":"numero"}],"respuestas":{"te":2,"varianza":0.1111111111111111},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-ii","modulo_orden":2}'::jsonb,1,'HISTORIA','editor','GLOBAL');
  ELSE
    UPDATE lms_core.ejercicios_practicos SET titulo='Tiempo esperado',enunciado='A tiene a=1,m=2,b=3. Calcula te y varianza.',query_maestra='',dificultad=2,configuracion_extra='{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-ii:2:1","campos":[{"clave":"te","etiqueta":"Te","tipo":"numero"},{"clave":"varianza","etiqueta":"Varianza","tipo":"numero"}],"respuestas":{"te":2,"varianza":0.1111111111111111},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-ii","modulo_orden":2}'::jsonb,orden=1,tipo_mision='HISTORIA',formato='editor',visibilidad='GLOBAL' WHERE id_ejercicio=ejercicio_id;
  END IF;
  SELECT id_ejercicio INTO ejercicio_id FROM lms_core.ejercicios_practicos WHERE id_modulo=modulo_id AND configuracion_extra->>'semilla_clave'='io-unach-v1:io-ii:2:2';
  IF ejercicio_id IS NULL THEN
    INSERT INTO lms_core.ejercicios_practicos(id_modulo,titulo,enunciado,query_maestra,dificultad,configuracion_extra,orden,tipo_mision,formato,visibilidad)
    VALUES(modulo_id,'Ruta secuencial','A(1,2,3) precede a B(2,3,4). Calcula media del proyecto y varianza total.','',3,'{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-ii:2:2","campos":[{"clave":"media","etiqueta":"Media","tipo":"numero"},{"clave":"varianza","etiqueta":"Varianza","tipo":"numero"}],"respuestas":{"media":5,"varianza":0.2222222222222222},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-ii","modulo_orden":2}'::jsonb,2,'HISTORIA','editor','GLOBAL');
  ELSE
    UPDATE lms_core.ejercicios_practicos SET titulo='Ruta secuencial',enunciado='A(1,2,3) precede a B(2,3,4). Calcula media del proyecto y varianza total.',query_maestra='',dificultad=3,configuracion_extra='{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-ii:2:2","campos":[{"clave":"media","etiqueta":"Media","tipo":"numero"},{"clave":"varianza","etiqueta":"Varianza","tipo":"numero"}],"respuestas":{"media":5,"varianza":0.2222222222222222},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-ii","modulo_orden":2}'::jsonb,orden=2,tipo_mision='HISTORIA',formato='editor',visibilidad='GLOBAL' WHERE id_ejercicio=ejercicio_id;
  END IF;
  SELECT id_ejercicio INTO ejercicio_id FROM lms_core.ejercicios_practicos WHERE id_modulo=modulo_id AND configuracion_extra->>'semilla_clave'='io-unach-v1:io-ii:2:3';
  IF ejercicio_id IS NULL THEN
    INSERT INTO lms_core.ejercicios_practicos(id_modulo,titulo,enunciado,query_maestra,dificultad,configuracion_extra,orden,tipo_mision,formato,visibilidad)
    VALUES(modulo_id,'Cumplir la media','En esa red el plazo es 5. Usando la aproximación normal calcula z y probabilidad de terminar antes o en el plazo (0 a 1).','',4,'{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-ii:2:3","campos":[{"clave":"z","etiqueta":"Z","tipo":"numero"},{"clave":"probabilidad","etiqueta":"Probabilidad","tipo":"numero"}],"respuestas":{"z":0,"probabilidad":0.5000000005},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-ii","modulo_orden":2}'::jsonb,3,'HISTORIA','editor','GLOBAL');
  ELSE
    UPDATE lms_core.ejercicios_practicos SET titulo='Cumplir la media',enunciado='En esa red el plazo es 5. Usando la aproximación normal calcula z y probabilidad de terminar antes o en el plazo (0 a 1).',query_maestra='',dificultad=4,configuracion_extra='{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-ii:2:3","campos":[{"clave":"z","etiqueta":"Z","tipo":"numero"},{"clave":"probabilidad","etiqueta":"Probabilidad","tipo":"numero"}],"respuestas":{"z":0,"probabilidad":0.5000000005},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-ii","modulo_orden":2}'::jsonb,orden=3,tipo_mision='HISTORIA',formato='editor',visibilidad='GLOBAL' WHERE id_ejercicio=ejercicio_id;
  END IF;
  SELECT id_curso INTO STRICT curso_id FROM lms_core.cursos WHERE titulo='IO II — Modelos Estocásticos y Proyectos' AND materia_slug='io';
  INSERT INTO lms_core.modulos(id_curso,titulo,orden,descripcion,xp_requerida,objetivos,errores_comunes)
  VALUES(curso_id,'Inventarios deterministas',3,'EOQ equilibra pedir y mantener con demanda anual D, costo por pedido S y costo anual por unidad H. Supone demanda constante, reposición instantánea y ausencia de faltantes.',60,'["Calcular EOQ y lote de producción","Comparar faltantes y descuentos"]'::jsonb,'["Mezclar costos mensuales con demanda anual","Ignorar el costo de compra cuando cambia el precio"]'::jsonb)
  ON CONFLICT(id_curso,orden) DO UPDATE SET titulo=EXCLUDED.titulo,descripcion=EXCLUDED.descripcion,xp_requerida=EXCLUDED.xp_requerida,objetivos=EXCLUDED.objetivos,errores_comunes=EXCLUDED.errores_comunes
  RETURNING id_modulo INTO modulo_id;
  SELECT id_ejercicio INTO ejercicio_id FROM lms_core.ejercicios_practicos WHERE id_modulo=modulo_id AND configuracion_extra->>'semilla_clave'='io-unach-v1:io-ii:3:1';
  IF ejercicio_id IS NULL THEN
    INSERT INTO lms_core.ejercicios_practicos(id_modulo,titulo,enunciado,query_maestra,dificultad,configuracion_extra,orden,tipo_mision,formato,visibilidad)
    VALUES(modulo_id,'EOQ y pedidos','D=1000 unidades/año, S=10 por pedido, H=0.5 por unidad/año. Calcula Q y pedidos al año.','',2,'{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-ii:3:1","campos":[{"clave":"q","etiqueta":"Q","tipo":"numero"},{"clave":"pedidos","etiqueta":"Pedidos","tipo":"numero"}],"respuestas":{"q":200,"pedidos":5},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-ii","modulo_orden":3}'::jsonb,1,'HISTORIA','editor','GLOBAL');
  ELSE
    UPDATE lms_core.ejercicios_practicos SET titulo='EOQ y pedidos',enunciado='D=1000 unidades/año, S=10 por pedido, H=0.5 por unidad/año. Calcula Q y pedidos al año.',query_maestra='',dificultad=2,configuracion_extra='{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-ii:3:1","campos":[{"clave":"q","etiqueta":"Q","tipo":"numero"},{"clave":"pedidos","etiqueta":"Pedidos","tipo":"numero"}],"respuestas":{"q":200,"pedidos":5},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-ii","modulo_orden":3}'::jsonb,orden=1,tipo_mision='HISTORIA',formato='editor',visibilidad='GLOBAL' WHERE id_ejercicio=ejercicio_id;
  END IF;
  SELECT id_ejercicio INTO ejercicio_id FROM lms_core.ejercicios_practicos WHERE id_modulo=modulo_id AND configuracion_extra->>'semilla_clave'='io-unach-v1:io-ii:3:2';
  IF ejercicio_id IS NULL THEN
    INSERT INTO lms_core.ejercicios_practicos(id_modulo,titulo,enunciado,query_maestra,dificultad,configuracion_extra,orden,tipo_mision,formato,visibilidad)
    VALUES(modulo_id,'Producción gradual','Con D=1000,S=10,H=0.5 y producción P=2000/año, calcula EPQ y máximo inventario.','',3,'{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-ii:3:2","campos":[{"clave":"q","etiqueta":"Q","tipo":"numero"},{"clave":"inventario_maximo","etiqueta":"Inventario maximo","tipo":"numero"}],"respuestas":{"q":282.842712474619,"inventario_maximo":141.4213562373095},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-ii","modulo_orden":3}'::jsonb,2,'HISTORIA','editor','GLOBAL');
  ELSE
    UPDATE lms_core.ejercicios_practicos SET titulo='Producción gradual',enunciado='Con D=1000,S=10,H=0.5 y producción P=2000/año, calcula EPQ y máximo inventario.',query_maestra='',dificultad=3,configuracion_extra='{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-ii:3:2","campos":[{"clave":"q","etiqueta":"Q","tipo":"numero"},{"clave":"inventario_maximo","etiqueta":"Inventario maximo","tipo":"numero"}],"respuestas":{"q":282.842712474619,"inventario_maximo":141.4213562373095},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-ii","modulo_orden":3}'::jsonb,orden=2,tipo_mision='HISTORIA',formato='editor',visibilidad='GLOBAL' WHERE id_ejercicio=ejercicio_id;
  END IF;
  SELECT id_ejercicio INTO ejercicio_id FROM lms_core.ejercicios_practicos WHERE id_modulo=modulo_id AND configuracion_extra->>'semilla_clave'='io-unach-v1:io-ii:3:3';
  IF ejercicio_id IS NULL THEN
    INSERT INTO lms_core.ejercicios_practicos(id_modulo,titulo,enunciado,query_maestra,dificultad,configuracion_extra,orden,tipo_mision,formato,visibilidad)
    VALUES(modulo_id,'Faltantes y descuento','Con D=1000,S=10,H=0.5 y p=2 por unidad pendiente/año calcula Q con faltantes. Por separado, usa D=1000,S=10,i=0.1 y precios 10 desde 0,9 desde 500: ¿qué Q minimiza el costo total?','',4,'{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-ii:3:3","campos":[{"clave":"q_faltantes","etiqueta":"Q faltantes","tipo":"numero"},{"clave":"q_descuento","etiqueta":"Q descuento","tipo":"numero"}],"respuestas":{"q_faltantes":223.60679774997897,"q_descuento":500},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-ii","modulo_orden":3}'::jsonb,3,'HISTORIA','editor','GLOBAL');
  ELSE
    UPDATE lms_core.ejercicios_practicos SET titulo='Faltantes y descuento',enunciado='Con D=1000,S=10,H=0.5 y p=2 por unidad pendiente/año calcula Q con faltantes. Por separado, usa D=1000,S=10,i=0.1 y precios 10 desde 0,9 desde 500: ¿qué Q minimiza el costo total?',query_maestra='',dificultad=4,configuracion_extra='{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-ii:3:3","campos":[{"clave":"q_faltantes","etiqueta":"Q faltantes","tipo":"numero"},{"clave":"q_descuento","etiqueta":"Q descuento","tipo":"numero"}],"respuestas":{"q_faltantes":223.60679774997897,"q_descuento":500},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-ii","modulo_orden":3}'::jsonb,orden=3,tipo_mision='HISTORIA',formato='editor',visibilidad='GLOBAL' WHERE id_ejercicio=ejercicio_id;
  END IF;
  SELECT id_curso INTO STRICT curso_id FROM lms_core.cursos WHERE titulo='IO II — Modelos Estocásticos y Proyectos' AND materia_slug='io';
  INSERT INTO lms_core.modulos(id_curso,titulo,orden,descripcion,xp_requerida,objetivos,errores_comunes)
  VALUES(curso_id,'Inventarios con incertidumbre y período fijo',4,'Con demanda media d por día y plazo L, la demanda esperada durante entrega es dL. Si las demandas diarias son independientes con desviación sigma y plazo constante, la desviación durante entrega es sigma*sqrt(L).',90,'["Calcular stock de seguridad y reorden","Usar posición de inventario"]'::jsonb,'["Usar sigma*L en vez de sigma*sqrt(L)","Confundir inventario disponible con posición"]'::jsonb)
  ON CONFLICT(id_curso,orden) DO UPDATE SET titulo=EXCLUDED.titulo,descripcion=EXCLUDED.descripcion,xp_requerida=EXCLUDED.xp_requerida,objetivos=EXCLUDED.objetivos,errores_comunes=EXCLUDED.errores_comunes
  RETURNING id_modulo INTO modulo_id;
  SELECT id_ejercicio INTO ejercicio_id FROM lms_core.ejercicios_practicos WHERE id_modulo=modulo_id AND configuracion_extra->>'semilla_clave'='io-unach-v1:io-ii:4:1';
  IF ejercicio_id IS NULL THEN
    INSERT INTO lms_core.ejercicios_practicos(id_modulo,titulo,enunciado,query_maestra,dificultad,configuracion_extra,orden,tipo_mision,formato,visibilidad)
    VALUES(modulo_id,'Reorden sin incertidumbre','Demanda media 10/día y entrega en 4 días. Calcula el punto de reorden sin stock de seguridad.','',2,'{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-ii:4:1","campos":[{"clave":"r","etiqueta":"R","tipo":"numero"}],"respuestas":{"r":40},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-ii","modulo_orden":4}'::jsonb,1,'HISTORIA','editor','GLOBAL');
  ELSE
    UPDATE lms_core.ejercicios_practicos SET titulo='Reorden sin incertidumbre',enunciado='Demanda media 10/día y entrega en 4 días. Calcula el punto de reorden sin stock de seguridad.',query_maestra='',dificultad=2,configuracion_extra='{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-ii:4:1","campos":[{"clave":"r","etiqueta":"R","tipo":"numero"}],"respuestas":{"r":40},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-ii","modulo_orden":4}'::jsonb,orden=1,tipo_mision='HISTORIA',formato='editor',visibilidad='GLOBAL' WHERE id_ejercicio=ejercicio_id;
  END IF;
  SELECT id_ejercicio INTO ejercicio_id FROM lms_core.ejercicios_practicos WHERE id_modulo=modulo_id AND configuracion_extra->>'semilla_clave'='io-unach-v1:io-ii:4:2';
  IF ejercicio_id IS NULL THEN
    INSERT INTO lms_core.ejercicios_practicos(id_modulo,titulo,enunciado,query_maestra,dificultad,configuracion_extra,orden,tipo_mision,formato,visibilidad)
    VALUES(modulo_id,'Protección de demanda','d=10/día,L=4,sigma=3 por día,z=2. Calcula stock de seguridad y R.','',3,'{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-ii:4:2","campos":[{"clave":"seguridad","etiqueta":"Seguridad","tipo":"numero"},{"clave":"r","etiqueta":"R","tipo":"numero"}],"respuestas":{"seguridad":12,"r":52},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-ii","modulo_orden":4}'::jsonb,2,'HISTORIA','editor','GLOBAL');
  ELSE
    UPDATE lms_core.ejercicios_practicos SET titulo='Protección de demanda',enunciado='d=10/día,L=4,sigma=3 por día,z=2. Calcula stock de seguridad y R.',query_maestra='',dificultad=3,configuracion_extra='{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-ii:4:2","campos":[{"clave":"seguridad","etiqueta":"Seguridad","tipo":"numero"},{"clave":"r","etiqueta":"R","tipo":"numero"}],"respuestas":{"seguridad":12,"r":52},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-ii","modulo_orden":4}'::jsonb,orden=2,tipo_mision='HISTORIA',formato='editor',visibilidad='GLOBAL' WHERE id_ejercicio=ejercicio_id;
  END IF;
  SELECT id_ejercicio INTO ejercicio_id FROM lms_core.ejercicios_practicos WHERE id_modulo=modulo_id AND configuracion_extra->>'semilla_clave'='io-unach-v1:io-ii:4:3';
  IF ejercicio_id IS NULL THEN
    INSERT INTO lms_core.ejercicios_practicos(id_modulo,titulo,enunciado,query_maestra,dificultad,configuracion_extra,orden,tipo_mision,formato,visibilidad)
    VALUES(modulo_id,'Revisión periódica','d=10,T=5,L=4,sigma=3,z=2 y posición de inventario 40. Calcula nivel objetivo y pedido.','',4,'{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-ii:4:3","campos":[{"clave":"objetivo","etiqueta":"Objetivo","tipo":"numero"},{"clave":"q","etiqueta":"Q","tipo":"numero"}],"respuestas":{"objetivo":108,"q":68},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-ii","modulo_orden":4}'::jsonb,3,'HISTORIA','editor','GLOBAL');
  ELSE
    UPDATE lms_core.ejercicios_practicos SET titulo='Revisión periódica',enunciado='d=10,T=5,L=4,sigma=3,z=2 y posición de inventario 40. Calcula nivel objetivo y pedido.',query_maestra='',dificultad=4,configuracion_extra='{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-ii:4:3","campos":[{"clave":"objetivo","etiqueta":"Objetivo","tipo":"numero"},{"clave":"q","etiqueta":"Q","tipo":"numero"}],"respuestas":{"objetivo":108,"q":68},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-ii","modulo_orden":4}'::jsonb,orden=3,tipo_mision='HISTORIA',formato='editor',visibilidad='GLOBAL' WHERE id_ejercicio=ejercicio_id;
  END IF;
  SELECT id_curso INTO STRICT curso_id FROM lms_core.cursos WHERE titulo='IO II — Modelos Estocásticos y Proyectos' AND materia_slug='io';
  INSERT INTO lms_core.modulos(id_curso,titulo,orden,descripcion,xp_requerida,objetivos,errores_comunes)
  VALUES(curso_id,'Líneas de espera M/M/1 y M/M/s',5,'M/M/1 supone llegadas Poisson, servicios exponenciales, un servidor, población y capacidad ilimitadas y régimen estacionario. Usa tasas lambda y mu en la misma unidad. Si lambda>=mu, las medidas estacionarias no existen.',120,'["Comprobar estabilidad","Distinguir sistema y cola"]'::jsonb,'["Introducir minutos junto con tasas por hora","Usar mu total cuando el modelo espera mu por servidor"]'::jsonb)
  ON CONFLICT(id_curso,orden) DO UPDATE SET titulo=EXCLUDED.titulo,descripcion=EXCLUDED.descripcion,xp_requerida=EXCLUDED.xp_requerida,objetivos=EXCLUDED.objetivos,errores_comunes=EXCLUDED.errores_comunes
  RETURNING id_modulo INTO modulo_id;
  SELECT id_ejercicio INTO ejercicio_id FROM lms_core.ejercicios_practicos WHERE id_modulo=modulo_id AND configuracion_extra->>'semilla_clave'='io-unach-v1:io-ii:5:1';
  IF ejercicio_id IS NULL THEN
    INSERT INTO lms_core.ejercicios_practicos(id_modulo,titulo,enunciado,query_maestra,dificultad,configuracion_extra,orden,tipo_mision,formato,visibilidad)
    VALUES(modulo_id,'Utilización','Para M/M/1 lambda=2/h,mu=3/h, calcula rho y P0.','',2,'{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-ii:5:1","campos":[{"clave":"rho","etiqueta":"Rho","tipo":"numero"},{"clave":"p0","etiqueta":"P0","tipo":"numero"}],"respuestas":{"rho":0.6666666666666666,"p0":0.33333333333333337},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-ii","modulo_orden":5}'::jsonb,1,'HISTORIA','editor','GLOBAL');
  ELSE
    UPDATE lms_core.ejercicios_practicos SET titulo='Utilización',enunciado='Para M/M/1 lambda=2/h,mu=3/h, calcula rho y P0.',query_maestra='',dificultad=2,configuracion_extra='{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-ii:5:1","campos":[{"clave":"rho","etiqueta":"Rho","tipo":"numero"},{"clave":"p0","etiqueta":"P0","tipo":"numero"}],"respuestas":{"rho":0.6666666666666666,"p0":0.33333333333333337},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-ii","modulo_orden":5}'::jsonb,orden=1,tipo_mision='HISTORIA',formato='editor',visibilidad='GLOBAL' WHERE id_ejercicio=ejercicio_id;
  END IF;
  SELECT id_ejercicio INTO ejercicio_id FROM lms_core.ejercicios_practicos WHERE id_modulo=modulo_id AND configuracion_extra->>'semilla_clave'='io-unach-v1:io-ii:5:2';
  IF ejercicio_id IS NULL THEN
    INSERT INTO lms_core.ejercicios_practicos(id_modulo,titulo,enunciado,query_maestra,dificultad,configuracion_extra,orden,tipo_mision,formato,visibilidad)
    VALUES(modulo_id,'Esperar y permanecer','En ese sistema calcula Lq y W en horas.','',3,'{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-ii:5:2","campos":[{"clave":"lq","etiqueta":"Lq","tipo":"numero"},{"clave":"w","etiqueta":"W","tipo":"numero"}],"respuestas":{"lq":1.333333333333333,"w":1},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-ii","modulo_orden":5}'::jsonb,2,'HISTORIA','editor','GLOBAL');
  ELSE
    UPDATE lms_core.ejercicios_practicos SET titulo='Esperar y permanecer',enunciado='En ese sistema calcula Lq y W en horas.',query_maestra='',dificultad=3,configuracion_extra='{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-ii:5:2","campos":[{"clave":"lq","etiqueta":"Lq","tipo":"numero"},{"clave":"w","etiqueta":"W","tipo":"numero"}],"respuestas":{"lq":1.333333333333333,"w":1},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-ii","modulo_orden":5}'::jsonb,orden=2,tipo_mision='HISTORIA',formato='editor',visibilidad='GLOBAL' WHERE id_ejercicio=ejercicio_id;
  END IF;
  SELECT id_ejercicio INTO ejercicio_id FROM lms_core.ejercicios_practicos WHERE id_modulo=modulo_id AND configuracion_extra->>'semilla_clave'='io-unach-v1:io-ii:5:3';
  IF ejercicio_id IS NULL THEN
    INSERT INTO lms_core.ejercicios_practicos(id_modulo,titulo,enunciado,query_maestra,dificultad,configuracion_extra,orden,tipo_mision,formato,visibilidad)
    VALUES(modulo_id,'Dos servidores','Para lambda=2/h,mu=3/h por servidor,s=2 calcula Lq y Wq en horas.','',4,'{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-ii:5:3","campos":[{"clave":"lq","etiqueta":"Lq","tipo":"numero"},{"clave":"wq","etiqueta":"Wq","tipo":"numero"}],"respuestas":{"lq":0.08333333333333331,"wq":0.04166666666666666},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-ii","modulo_orden":5}'::jsonb,3,'HISTORIA','editor','GLOBAL');
  ELSE
    UPDATE lms_core.ejercicios_practicos SET titulo='Dos servidores',enunciado='Para lambda=2/h,mu=3/h por servidor,s=2 calcula Lq y Wq en horas.',query_maestra='',dificultad=4,configuracion_extra='{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-ii:5:3","campos":[{"clave":"lq","etiqueta":"Lq","tipo":"numero"},{"clave":"wq","etiqueta":"Wq","tipo":"numero"}],"respuestas":{"lq":0.08333333333333331,"wq":0.04166666666666666},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-ii","modulo_orden":5}'::jsonb,orden=3,tipo_mision='HISTORIA',formato='editor',visibilidad='GLOBAL' WHERE id_ejercicio=ejercicio_id;
  END IF;
  SELECT id_curso INTO STRICT curso_id FROM lms_core.cursos WHERE titulo='IO II — Modelos Estocásticos y Proyectos' AND materia_slug='io';
  INSERT INTO lms_core.modulos(id_curso,titulo,orden,descripcion,xp_requerida,objetivos,errores_comunes)
  VALUES(curso_id,'Cadenas de Markov',6,'Cada fila de P contiene probabilidades del próximo estado condicionado al actual y suma uno. Con vectores fila, la distribución evoluciona como p(n+1)=p(n)P. La hipótesis de Markov depende del estado actual, no de toda la historia.',150,'["Proyectar distribuciones por transición","Distinguir estacionaria de convergencia"]'::jsonb,'["Multiplicar en la orientación equivocada","Afirmar convergencia solo porque existe una estacionaria"]'::jsonb)
  ON CONFLICT(id_curso,orden) DO UPDATE SET titulo=EXCLUDED.titulo,descripcion=EXCLUDED.descripcion,xp_requerida=EXCLUDED.xp_requerida,objetivos=EXCLUDED.objetivos,errores_comunes=EXCLUDED.errores_comunes
  RETURNING id_modulo INTO modulo_id;
  SELECT id_ejercicio INTO ejercicio_id FROM lms_core.ejercicios_practicos WHERE id_modulo=modulo_id AND configuracion_extra->>'semilla_clave'='io-unach-v1:io-ii:6:1';
  IF ejercicio_id IS NULL THEN
    INSERT INTO lms_core.ejercicios_practicos(id_modulo,titulo,enunciado,query_maestra,dificultad,configuracion_extra,orden,tipo_mision,formato,visibilidad)
    VALUES(modulo_id,'Una transición','P=[[0.8,0.2],[0.3,0.7]] y p0=[1,0]. Calcula probabilidad de A y B después de un paso.','',2,'{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-ii:6:1","campos":[{"clave":"a","etiqueta":"A","tipo":"numero"},{"clave":"b","etiqueta":"B","tipo":"numero"}],"respuestas":{"a":0.8,"b":0.2},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-ii","modulo_orden":6}'::jsonb,1,'HISTORIA','editor','GLOBAL');
  ELSE
    UPDATE lms_core.ejercicios_practicos SET titulo='Una transición',enunciado='P=[[0.8,0.2],[0.3,0.7]] y p0=[1,0]. Calcula probabilidad de A y B después de un paso.',query_maestra='',dificultad=2,configuracion_extra='{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-ii:6:1","campos":[{"clave":"a","etiqueta":"A","tipo":"numero"},{"clave":"b","etiqueta":"B","tipo":"numero"}],"respuestas":{"a":0.8,"b":0.2},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-ii","modulo_orden":6}'::jsonb,orden=1,tipo_mision='HISTORIA',formato='editor',visibilidad='GLOBAL' WHERE id_ejercicio=ejercicio_id;
  END IF;
  SELECT id_ejercicio INTO ejercicio_id FROM lms_core.ejercicios_practicos WHERE id_modulo=modulo_id AND configuracion_extra->>'semilla_clave'='io-unach-v1:io-ii:6:2';
  IF ejercicio_id IS NULL THEN
    INSERT INTO lms_core.ejercicios_practicos(id_modulo,titulo,enunciado,query_maestra,dificultad,configuracion_extra,orden,tipo_mision,formato,visibilidad)
    VALUES(modulo_id,'Dos transiciones','Con la misma cadena calcula p2(A) y p2(B).','',3,'{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-ii:6:2","campos":[{"clave":"a","etiqueta":"A","tipo":"numero"},{"clave":"b","etiqueta":"B","tipo":"numero"}],"respuestas":{"a":0.7000000000000002,"b":0.30000000000000004},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-ii","modulo_orden":6}'::jsonb,2,'HISTORIA','editor','GLOBAL');
  ELSE
    UPDATE lms_core.ejercicios_practicos SET titulo='Dos transiciones',enunciado='Con la misma cadena calcula p2(A) y p2(B).',query_maestra='',dificultad=3,configuracion_extra='{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-ii:6:2","campos":[{"clave":"a","etiqueta":"A","tipo":"numero"},{"clave":"b","etiqueta":"B","tipo":"numero"}],"respuestas":{"a":0.7000000000000002,"b":0.30000000000000004},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-ii","modulo_orden":6}'::jsonb,orden=2,tipo_mision='HISTORIA',formato='editor',visibilidad='GLOBAL' WHERE id_ejercicio=ejercicio_id;
  END IF;
  SELECT id_ejercicio INTO ejercicio_id FROM lms_core.ejercicios_practicos WHERE id_modulo=modulo_id AND configuracion_extra->>'semilla_clave'='io-unach-v1:io-ii:6:3';
  IF ejercicio_id IS NULL THEN
    INSERT INTO lms_core.ejercicios_practicos(id_modulo,titulo,enunciado,query_maestra,dificultad,configuracion_extra,orden,tipo_mision,formato,visibilidad)
    VALUES(modulo_id,'Distribución estacionaria','Resuelve pi P=pi para la matriz anterior.','',4,'{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-ii:6:3","campos":[{"clave":"a","etiqueta":"A","tipo":"numero"},{"clave":"b","etiqueta":"B","tipo":"numero"}],"respuestas":{"a":0.6,"b":0.4},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-ii","modulo_orden":6}'::jsonb,3,'HISTORIA','editor','GLOBAL');
  ELSE
    UPDATE lms_core.ejercicios_practicos SET titulo='Distribución estacionaria',enunciado='Resuelve pi P=pi para la matriz anterior.',query_maestra='',dificultad=4,configuracion_extra='{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-ii:6:3","campos":[{"clave":"a","etiqueta":"A","tipo":"numero"},{"clave":"b","etiqueta":"B","tipo":"numero"}],"respuestas":{"a":0.6,"b":0.4},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-ii","modulo_orden":6}'::jsonb,orden=3,tipo_mision='HISTORIA',formato='editor',visibilidad='GLOBAL' WHERE id_ejercicio=ejercicio_id;
  END IF;
  SELECT id_curso INTO STRICT curso_id FROM lms_core.cursos WHERE titulo='IO II — Modelos Estocásticos y Proyectos' AND materia_slug='io';
  INSERT INTO lms_core.modulos(id_curso,titulo,orden,descripcion,xp_requerida,objetivos,errores_comunes)
  VALUES(curso_id,'Programación no lineal',7,'Sección dorada estrecha un intervalo donde la función es unimodal. Newton aplicado a f prima usa x siguiente=x-f prima/f segunda para buscar estacionarios; puede no converger y requiere derivadas válidas.',180,'["Comparar sección dorada y Newton","Formular condiciones de Lagrange"]'::jsonb,'["Declarar óptimo global cualquier punto estacionario","Aplicar sección dorada sin verificar unimodalidad"]'::jsonb)
  ON CONFLICT(id_curso,orden) DO UPDATE SET titulo=EXCLUDED.titulo,descripcion=EXCLUDED.descripcion,xp_requerida=EXCLUDED.xp_requerida,objetivos=EXCLUDED.objetivos,errores_comunes=EXCLUDED.errores_comunes
  RETURNING id_modulo INTO modulo_id;
  SELECT id_ejercicio INTO ejercicio_id FROM lms_core.ejercicios_practicos WHERE id_modulo=modulo_id AND configuracion_extra->>'semilla_clave'='io-unach-v1:io-ii:7:1';
  IF ejercicio_id IS NULL THEN
    INSERT INTO lms_core.ejercicios_practicos(id_modulo,titulo,enunciado,query_maestra,dificultad,configuracion_extra,orden,tipo_mision,formato,visibilidad)
    VALUES(modulo_id,'Newton en una parábola','f(x)=(x-3)^2+2, inicia Newton en x0=0. Calcula x estacionario y f(x).','',2,'{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-ii:7:1","campos":[{"clave":"x","etiqueta":"X","tipo":"numero"},{"clave":"fx","etiqueta":"Fx","tipo":"numero"}],"respuestas":{"x":3,"fx":2},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-ii","modulo_orden":7}'::jsonb,1,'HISTORIA','editor','GLOBAL');
  ELSE
    UPDATE lms_core.ejercicios_practicos SET titulo='Newton en una parábola',enunciado='f(x)=(x-3)^2+2, inicia Newton en x0=0. Calcula x estacionario y f(x).',query_maestra='',dificultad=2,configuracion_extra='{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-ii:7:1","campos":[{"clave":"x","etiqueta":"X","tipo":"numero"},{"clave":"fx","etiqueta":"Fx","tipo":"numero"}],"respuestas":{"x":3,"fx":2},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-ii","modulo_orden":7}'::jsonb,orden=1,tipo_mision='HISTORIA',formato='editor',visibilidad='GLOBAL' WHERE id_ejercicio=ejercicio_id;
  END IF;
  SELECT id_ejercicio INTO ejercicio_id FROM lms_core.ejercicios_practicos WHERE id_modulo=modulo_id AND configuracion_extra->>'semilla_clave'='io-unach-v1:io-ii:7:2';
  IF ejercicio_id IS NULL THEN
    INSERT INTO lms_core.ejercicios_practicos(id_modulo,titulo,enunciado,query_maestra,dificultad,configuracion_extra,orden,tipo_mision,formato,visibilidad)
    VALUES(modulo_id,'Clasificación local','Para esa función calcula f segunda y clasifica el estacionario.','',3,'{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-ii:7:2","campos":[{"clave":"segunda","etiqueta":"Segunda","tipo":"numero"},{"clave":"tipo","etiqueta":"Tipo","tipo":"opcion","opciones":["mínimo","máximo","inflexión"]}],"respuestas":{"segunda":2,"tipo":"mínimo"},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-ii","modulo_orden":7}'::jsonb,2,'HISTORIA','editor','GLOBAL');
  ELSE
    UPDATE lms_core.ejercicios_practicos SET titulo='Clasificación local',enunciado='Para esa función calcula f segunda y clasifica el estacionario.',query_maestra='',dificultad=3,configuracion_extra='{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-ii:7:2","campos":[{"clave":"segunda","etiqueta":"Segunda","tipo":"numero"},{"clave":"tipo","etiqueta":"Tipo","tipo":"opcion","opciones":["mínimo","máximo","inflexión"]}],"respuestas":{"segunda":2,"tipo":"mínimo"},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-ii","modulo_orden":7}'::jsonb,orden=2,tipo_mision='HISTORIA',formato='editor',visibilidad='GLOBAL' WHERE id_ejercicio=ejercicio_id;
  END IF;
  SELECT id_ejercicio INTO ejercicio_id FROM lms_core.ejercicios_practicos WHERE id_modulo=modulo_id AND configuracion_extra->>'semilla_clave'='io-unach-v1:io-ii:7:3';
  IF ejercicio_id IS NULL THEN
    INSERT INTO lms_core.ejercicios_practicos(id_modulo,titulo,enunciado,query_maestra,dificultad,configuracion_extra,orden,tipo_mision,formato,visibilidad)
    VALUES(modulo_id,'Lagrange','Maximiza xy con x+y=10 y x,y>=0. Calcula x,y y producto máximo.','',4,'{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-ii:7:3","campos":[{"clave":"x","etiqueta":"X","tipo":"numero"},{"clave":"y","etiqueta":"Y","tipo":"numero"},{"clave":"producto","etiqueta":"Producto","tipo":"numero"}],"respuestas":{"x":5,"y":5,"producto":25},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-ii","modulo_orden":7}'::jsonb,3,'HISTORIA','editor','GLOBAL');
  ELSE
    UPDATE lms_core.ejercicios_practicos SET titulo='Lagrange',enunciado='Maximiza xy con x+y=10 y x,y>=0. Calcula x,y y producto máximo.',query_maestra='',dificultad=4,configuracion_extra='{"tipo_validacion":"NUMERICO","semilla_clave":"io-unach-v1:io-ii:7:3","campos":[{"clave":"x","etiqueta":"X","tipo":"numero"},{"clave":"y","etiqueta":"Y","tipo":"numero"},{"clave":"producto","etiqueta":"Producto","tipo":"numero"}],"respuestas":{"x":5,"y":5,"producto":25},"tolerancia":{"abs":0.001,"rel":0.001},"curso_clave":"io-ii","modulo_orden":7}'::jsonb,orden=3,tipo_mision='HISTORIA',formato='editor',visibilidad='GLOBAL' WHERE id_ejercicio=ejercicio_id;
  END IF;
END;
$semilla$;
COMMIT;
